/* Dashboard half of the Remote Desktop peer connection.
 *
 * The agent half has been in the tree the whole time (webrtc_stream.rs +
 * input.rs); only this side was removed. The protocol it speaks is fixed by
 * that file, so everything here is written to match it exactly rather than to
 * taste:
 *
 *   • The DASHBOARD offers. The agent long-polls webrtc-signal for a
 *     `kind=offer` addressed to it, answers, and posts the answer back.
 *   • The DASHBOARD creates the DataChannel. The agent only has
 *     `on_data_channel`, so if we wait for one we wait forever.
 *   • Control frames are JSON text, tagged `t`, snake_case. Key codes are
 *     `KeyboardEvent.code` verbatim ("KeyA", "Enter", "F5") — input.rs maps
 *     those directly.
 *   • Mouse position is NORMALISED 0..1. The agent multiplies by its own
 *     monitor size, so the dashboard never needs to know the real resolution
 *     and a resized video element stays correct.
 */
import { supabase } from './supabase';
import { startRelaySession, relayFallbackSupported } from './relayClient';

const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL as string) ?? '';
const ANON_KEY = (import.meta.env.VITE_SUPABASE_ANON_KEY as string) ?? '';

export type ControlOut =
  | { t: 'hello'; proto: number }
  | { t: 'mouse_move'; x: number; y: number }
  | { t: 'mouse_button'; btn: 'left' | 'right' | 'middle'; down: boolean }
  | { t: 'mouse_wheel'; dx: number; dy: number }
  | { t: 'key'; code: string; down: boolean }
  | { t: 'clip_set'; text: string }
  | { t: 'clip_get' }
  | { t: 'ping'; id: number }
  | { t: 'set_quality'; width: number; bitrate_kbps: number };

export type ControlIn =
  | { t: 'screen_info'; w: number; h: number; scale: number }
  | { t: 'clip_data'; text: string }
  | { t: 'pong'; id: number };

export type Phase =
  | 'idle' | 'signalling' | 'connecting' | 'connected' | 'failed' | 'closed';

export type SessionHooks = {
  onPhase: (p: Phase, detail?: string) => void;
  onTrack: (stream: MediaStream) => void;
  onScreenInfo?: (w: number, h: number) => void;
  onClipboard?: (text: string) => void;
  /** Round-trip time in ms, measured over the control channel. */
  onLatency?: (ms: number) => void;
};

async function authHeaders(): Promise<Record<string, string>> {
  const { data } = await supabase.auth.getSession();
  return {
    apikey: ANON_KEY,
    Authorization: `Bearer ${data.session?.access_token ?? ANON_KEY}`,
    'Content-Type': 'application/json',
  };
}

async function postSignal(
  sessionId: string, agentId: string, kind: 'offer' | 'ice_candidate', payload: unknown,
) {
  const resp = await fetch(`${SUPABASE_URL}/functions/v1/webrtc-signal`, {
    method: 'POST',
    headers: await authHeaders(),
    body: JSON.stringify({
      session_id: sessionId, agent_id: agentId, direction: 'to_agent', kind, payload,
    }),
  });
  if (!resp.ok) throw new Error(`signal ${kind} ${resp.status}: ${await resp.text().catch(() => '')}`);
}

async function fetchIceServers(agentId: string): Promise<RTCIceServer[]> {
  try {
    const resp = await fetch(`${SUPABASE_URL}/functions/v1/webrtc-turn-credentials`, {
      method: 'POST',
      headers: await authHeaders(),
      body: JSON.stringify({ agent_id: agentId }),
    });
    if (resp.ok) {
      const body = await resp.json() as { iceServers?: RTCIceServer[] };
      if (body.iceServers?.length) return body.iceServers;
    }
  } catch { /* fall through to the public default */ }
  // A direct LAN or same-host connection needs no relay at all, so a failure
  // here is not fatal — it only removes the ability to traverse a symmetric
  // NAT. Better a session that works on the office network than no session.
  return [{ urls: 'stun:stun.l.google.com:19302' }];
}

/**
 * Establishes the connection and returns a handle for driving it.
 *
 * `sessionId` is generated by the caller so it can be posted alongside the
 * offer; the agent echoes it back on the answer.
 */
export function startRemoteSession(agentId: string, hooks: SessionHooks) {
  const sessionId = crypto.randomUUID();
  let pc: RTCPeerConnection | null = null;
  let dc: RTCDataChannel | null = null;
  let stopped = false;
  let pollTimer: number | null = null;
  let pingTimer: number | null = null;
  let since = new Date(Date.now() - 5_000).toISOString();
  const pending = new Map<number, number>(); // ping id -> sent-at

  const send = (msg: ControlOut) => {
    if (dc?.readyState === 'open') dc.send(JSON.stringify(msg));
  };

  const stop = () => {
    if (stopped) return;
    stopped = true;
    if (pollTimer) window.clearTimeout(pollTimer);
    if (pingTimer) window.clearInterval(pingTimer);
    try { dc?.close(); } catch { /* already gone */ }
    try { pc?.close(); } catch { /* already gone */ }
    hooks.onPhase('closed');
  };

  (async () => {
    try {
      hooks.onPhase('signalling');
      pc = new RTCPeerConnection({
        iceServers: await fetchIceServers(agentId),
        // Trickle everything as it is discovered rather than waiting for the
        // full gather; the first usable pair is usually found in well under a
        // second on a LAN and waiting for the whole set adds dead time before
        // the first frame.
        bundlePolicy: 'max-bundle',
      });

      // We must be the one to create this: the agent only implements
      // on_data_channel. Label is arbitrary but kept as "control" to match the
      // agent's log line. Ordered+reliable is right for input — dropping a
      // keyup would leave a key stuck down on someone else's machine.
      dc = pc.createDataChannel('control', { ordered: true });

      dc.onopen = () => {
        send({ t: 'hello', proto: 1 });
        // Round-trip probe. This measures the CONTROL path specifically, which
        // is what determines how immediate typing feels — video latency is a
        // separate pipeline and much larger.
        pingTimer = window.setInterval(() => {
          const id = Date.now() & 0xffffffff;
          pending.set(id, performance.now());
          send({ t: 'ping', id });
        }, 2000);
      };

      dc.onmessage = (e) => {
        let msg: ControlIn;
        try { msg = JSON.parse(e.data as string) as ControlIn; } catch { return; }
        if (msg.t === 'screen_info') hooks.onScreenInfo?.(msg.w, msg.h);
        else if (msg.t === 'clip_data') hooks.onClipboard?.(msg.text);
        else if (msg.t === 'pong') {
          const sent = pending.get(msg.id);
          if (sent !== undefined) {
            pending.delete(msg.id);
            hooks.onLatency?.(Math.round(performance.now() - sent));
          }
        }
      };

      // Receive-only video. The agent adds its track to the answer, so we have
      // to declare the direction up front or there is nothing to answer into.
      pc.addTransceiver('video', { direction: 'recvonly' });

      pc.ontrack = (e) => {
        const [stream] = e.streams;
        if (stream) hooks.onTrack(stream);
        // Ask the browser for the shallowest jitter buffer it will give us.
        // Chrome's default target is tuned for smooth playback of conference
        // video and adds well over 100 ms; for remote control, a dropped frame
        // is far cheaper than a late one.
        try {
          const r = e.receiver as RTCRtpReceiver & { playoutDelayHint?: number };
          r.playoutDelayHint = 0;
        } catch { /* not supported — no harm */ }
      };

      // Candidates are BUFFERED until the offer has been posted.
      //
      // onicecandidate starts firing the instant setLocalDescription resolves,
      // which is before the offer POST completes. The agent begins its
      // per-session candidate poll at the OFFER's created_at, so any candidate
      // that reached the table first is behind that cursor and is never read.
      // The symptom is precise and was exactly what we saw: the agent gathers
      // its own candidates, receives none of ours, and logs "pingAllCandidates
      // called with no candidate pairs" until ICE gives up.
      //
      // Buffering guarantees every candidate row is newer than the offer row.
      let offerPosted = false;
      const queued: RTCIceCandidateInit[] = [];
      const shipCandidate = (c: RTCIceCandidateInit) => {
        void postSignal(sessionId, agentId, 'ice_candidate', c)
          .catch(() => { /* a lost candidate is survivable; others remain */ });
      };
      pc.onicecandidate = (e) => {
        if (!e.candidate) return;
        const json = e.candidate.toJSON();
        if (offerPosted) shipCandidate(json);
        else queued.push(json);
      };

      // Fail fast rather than waiting for ICE to give up on its own.
      //
      // WebRTC's own failure detection takes roughly 30 seconds, which makes a
      // retry loop useless: three attempts would be a minute and a half of
      // spinner. A pair that is going to work on a LAN is found in well under a
      // second, and via a relay in two or three — so if nothing has connected
      // after this long, another attempt is a better use of the time than
      // continuing to wait. Each fresh offer re-gathers candidates, which is
      // what actually changes the outcome.
      const CONNECT_DEADLINE_MS = 8_000;
      let settled = false;
      const watchdog = window.setTimeout(() => {
        if (settled || stopped) return;
        if (pc?.connectionState !== 'connected') {
          hooks.onPhase('failed', `no usable network path within ${CONNECT_DEADLINE_MS / 1000}s`);
        }
      }, CONNECT_DEADLINE_MS);

      pc.onconnectionstatechange = () => {
        const st = pc?.connectionState;
        if (st === 'connected') {
          settled = true;
          window.clearTimeout(watchdog);
          hooks.onPhase('connected');
        } else if (st === 'connecting') hooks.onPhase('connecting');
        else if (st === 'failed') {
          settled = true;
          window.clearTimeout(watchdog);
          hooks.onPhase('failed', 'peer connection failed');
        } else if (st === 'closed' || st === 'disconnected') {
          window.clearTimeout(watchdog);
          hooks.onPhase('closed');
        }
      };

      const offer = await pc.createOffer();
      await pc.setLocalDescription(offer);
      await postSignal(sessionId, agentId, 'offer', {
        type: offer.type, sdp: offer.sdp,
      });
      // Only now can candidates be written, so that every one of them sorts
      // after the offer for the agent's poll cursor.
      offerPosted = true;
      for (const c of queued.splice(0)) shipCandidate(c);
      hooks.onPhase('connecting');

      // Poll for the answer and the agent's candidates. The endpoint long-polls
      // for up to ~25s, so this is one open request rather than a busy loop.
      const poll = async () => {
        if (stopped) return;
        try {
          const url = `${SUPABASE_URL}/functions/v1/webrtc-signal`
            + `?session_id=${encodeURIComponent(sessionId)}`
            + `&direction=to_dashboard&since=${encodeURIComponent(since)}`;
          const resp = await fetch(url, { headers: await authHeaders() });
          if (resp.ok) {
            const body = await resp.json() as {
              messages: Array<{ kind: string; payload: unknown; created_at: string }>;
            };
            for (const m of body.messages) {
              since = m.created_at;
              if (stopped || !pc) break;
              if (m.kind === 'answer') {
                // The agent posts `{ sdp }` with NO `type` field, so this has to
                // be supplied here: RTCSessionDescription throws without it, and
                // that exception was being swallowed by the catch below — the
                // dashboard silently never left have-local-offer while the agent
                // sat waiting for connectivity checks that could not come.
                const p = m.payload as { sdp?: string; type?: RTCSdpType };
                if (!p.sdp) continue;
                if (pc.signalingState !== 'stable') {
                  await pc.setRemoteDescription({ type: p.type ?? 'answer', sdp: p.sdp });
                }
              } else if (m.kind === 'ice_candidate') {
                try {
                  await pc.addIceCandidate(new RTCIceCandidate(m.payload as RTCIceCandidateInit));
                } catch { /* candidate arrived before the answer; harmless */ }
              }
            }
          }
        } catch { /* transient — the retry below covers it */ }
        if (!stopped) pollTimer = window.setTimeout(() => void poll(), 250);
      };
      void poll();
    } catch (e) {
      hooks.onPhase('failed', e instanceof Error ? e.message : String(e));
    }
  })();

  return {
    sessionId,
    stop,
    send,
    /** Normalised pointer position, computed from the video element's own box. */
    sendPointer(el: HTMLVideoElement, clientX: number, clientY: number) {
      const r = el.getBoundingClientRect();
      if (r.width === 0 || r.height === 0) return;
      // object-fit: contain letterboxes the video, so the drawn area is smaller
      // than the element. Mapping against the element box would put the cursor
      // progressively further off toward the edges whenever the aspect ratios
      // differ — which they do on any non-16:9 agent screen.
      const vw = el.videoWidth || r.width;
      const vh = el.videoHeight || r.height;
      const scale = Math.min(r.width / vw, r.height / vh);
      const drawnW = vw * scale;
      const drawnH = vh * scale;
      const offX = (r.width - drawnW) / 2;
      const offY = (r.height - drawnH) / 2;
      const x = (clientX - r.left - offX) / drawnW;
      const y = (clientY - r.top - offY) / drawnH;
      if (x < 0 || x > 1 || y < 0 || y > 1) return; // in the letterbox, not the screen
      send({ t: 'mouse_move', x, y });
    },
  };
}

export type RemoteSession = ReturnType<typeof startRemoteSession>;

/**
 * WebRTC first, relay fallback second — the "works on any network" entry point.
 *
 * Tries a direct/TURN WebRTC session (low latency). If that fails to connect
 * before it ever reached `connected` — which is what happens when the employee
 * is on a UDP-blocked network — it silently switches to the TLS-443 relay
 * (relayClient.ts) reusing the SAME session id, so the agent's relay room
 * matches. The returned handle proxies to whichever transport is live, so the
 * UI (RemoteStage) uses it exactly like a plain session.
 */
export function startRemoteSessionWithFallback(
  agentId: string,
  hooks: SessionHooks,
): RemoteSession {
  let usingRelay = false;
  let everConnected = false;
  let fellBack = false;
  // Assigned immediately below; the proxy methods read it live so a switch to
  // the relay transparently re-points send()/sendPointer().
  let active: RemoteSession;

  const wrapped: SessionHooks = {
    ...hooks,
    onPhase: (p, detail) => {
      if (p === 'connected') everConnected = true;
      // A pre-connection WebRTC failure is the trigger to fall back, not an
      // error to show. Only fall back once, and only if the browser can decode
      // (WebCodecs); otherwise surface the failure honestly.
      if (!usingRelay && !everConnected && p === 'failed' && !fellBack) {
        if (!relayFallbackSupported()) {
          hooks.onPhase('failed', 'this browser cannot use the relay fallback (needs WebCodecs)');
          return;
        }
        fellBack = true;
        usingRelay = true;
        try { active.stop(); } catch { /* already down */ }
        hooks.onPhase('connecting', 'Direct path blocked — connecting via relay…');
        active = startRelaySession(agentId, active.sessionId, wrapped) as unknown as RemoteSession;
        return; // swallow the WebRTC failure; the relay is taking over
      }
      hooks.onPhase(p, detail);
    },
  };

  active = startRemoteSession(agentId, wrapped);
  const sessionId = active.sessionId;

  return {
    sessionId,
    stop: () => { try { active.stop(); } catch { /* */ } },
    send: (m) => active.send(m),
    sendPointer: (el, x, y) => active.sendPointer(el, x, y),
  };
}
