// GET /functions/v1/oauth-mobile-retrieve?state=...
//
// Mobile app polls this endpoint every ~1 sec after kicking off OAuth.
// Returns the deposited PKCE `code` for the matching state and deletes
// the row in the same call so the code can't be replayed. Returns 404
// if nothing has been deposited yet (app keeps polling).
//
// Anon-key auth is fine here — even though anyone with the state value
// could read the code, the OAuth state is itself a PKCE-random secret
// generated by supabase-js (~128 bits of entropy) and the code is also
// one-shot. A leak would require the attacker to know the same state,
// which is only ever known to the originating app instance.

import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.4";
import { corsHeaders } from "../_shared/cors.ts";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });
  if (req.method !== "GET") return json({ error: "method not allowed" }, 405);

  const url = new URL(req.url);
  const state = (url.searchParams.get("state") ?? "").trim();

  // SECURITY FIX (audit C3): the former `latest=true` mode returned the most
  // recent handoff row to ANY caller with no secret — during any user's login
  // an attacker could poll and grab their one-time OAuth code, taking over the
  // account. It has been removed. Retrieval now REQUIRES the caller's own PKCE
  // `state` (a ~128-bit secret generated client-side and known only to the
  // originating app), so only the app that started the flow can collect its
  // code. The mobile client must use the PKCE (state-keyed) flow; an
  // implicit-flow client that relied on `latest=true` must be updated to pass
  // its state.
  if (!state) {
    return json({ error: "state required" }, 400);
  }
  // Reject absurd values early — state is a fixed-size random string.
  if (state.length > 512) {
    return json({ error: "invalid state" }, 400);
  }

  const admin = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
    auth: { autoRefreshToken: false, persistSession: false },
  });

  // Atomic read-and-delete via DELETE ... RETURNING. PostgREST exposes
  // DELETE with `select` to get the deleted row back.
  const { data, error } = await admin
    .from("oauth_mobile_handoff")
    .delete()
    .eq("state", state)
    .select("code")
    .maybeSingle();
  if (error) return json({ error: error.message }, 500);
  if (!data?.code) return json({ ready: false }, 404);

  return json({ ready: true, code: data.code });
});

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status, headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}
