// GET /functions/v1/oauth-mobile-retrieve?state=...
//
// Mobile app polls this endpoint every ~1 sec after kicking off OAuth.
// Returns the deposited PKCE `code` for the matching state and deletes
// the row in the same call so the code can't be replayed. Returns 404
// if nothing has been deposited yet (app keeps polling).
//
// Anon-key auth is fine here — even though anyone with the state value
// could read the code, the OAuth state is itself a PKCE-random secret
// generated by supabase-js (~128 bits of entropy) and the code is also
// one-shot. A leak would require the attacker to know the same state,
// which is only ever known to the originating app instance.

import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.4";
import { corsHeaders } from "../_shared/cors.ts";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });
  if (req.method !== "GET") return json({ error: "method not allowed" }, 405);

  const url = new URL(req.url);
  const state = (url.searchParams.get("state") ?? "").trim();
  const latest = url.searchParams.get("latest") === "true";

  if (!state && !latest) {
    return json({ error: "state OR latest=true required" }, 400);
  }

  const admin = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
    auth: { autoRefreshToken: false, persistSession: false },
  });

  // Two modes:
  //   - state-keyed: PKCE flow where the app knows the state value
  //     because supabase-js generated it client-side.
  //   - latest=true: implicit flow where the state in the hash is
  //     server-generated and the app doesn't know it. The app polls
  //     for ANY entry deposited in the last 60 sec — fine for single-
  //     device single-flow which is always the case on a phone.
  if (latest) {
    const { data, error } = await admin
      .from("oauth_mobile_handoff")
      .select("state, code")
      .gte("created_at", new Date(Date.now() - 60_000).toISOString())
      .order("created_at", { ascending: false })
      .limit(1)
      .maybeSingle();
    if (error) return json({ error: error.message }, 500);
    if (!data?.code) return json({ ready: false }, 404);
    // Delete by primary key (state) so the code isn't replayed.
    await admin.from("oauth_mobile_handoff").delete().eq("state", data.state);
    return json({ ready: true, code: data.code });
  }

  // Atomic read-and-delete via DELETE ... RETURNING. PostgREST exposes
  // DELETE with `select` to get the deleted row back.
  const { data, error } = await admin
    .from("oauth_mobile_handoff")
    .delete()
    .eq("state", state)
    .select("code")
    .maybeSingle();
  if (error) return json({ error: error.message }, 500);
  if (!data?.code) return json({ ready: false }, 404);

  return json({ ready: true, code: data.code });
});

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status, headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}
