-- 0014_create_customer_rpc.sql
-- RPC for partner/super-admin to atomically register a new customer org + issue a license.

create or replace function public.create_customer_with_license(
  p_org_name        text,
  p_plan_id         uuid,
  p_seat_count      int default null,
  p_owner_email     text default null,    -- if provided, will be invited
  p_partner_id      uuid default null,    -- super-admin can override; partners must use their own
  p_notes           text default null
)
returns table(
  organization_id uuid,
  license_id      uuid,
  license_key     text,
  expires_at      timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_caller       uuid := auth.uid();
  v_caller_role  text;
  v_caller_partner uuid;
  v_partner_id   uuid;
  v_seats        int;
  v_org_id       uuid;
  v_license_id   uuid;
  v_license_key  text;
  v_expires_at   timestamptz;
  v_billing      text;
begin
  if v_caller is null then
    raise exception 'unauthenticated' using errcode = '42501';
  end if;

  select app_role, partner_id into v_caller_role, v_caller_partner
  from public.app_users where user_id = v_caller;

  if v_caller_role not in ('super_admin','partner') then
    raise exception 'forbidden: only super_admin or partner can create customers' using errcode = '42501';
  end if;

  -- Resolve partner_id
  if v_caller_role = 'super_admin' then
    v_partner_id := p_partner_id;  -- nullable; null = direct customer
  else
    if p_partner_id is not null and p_partner_id <> v_caller_partner then
      raise exception 'partners can only register customers under themselves' using errcode = '42501';
    end if;
    v_partner_id := v_caller_partner;
  end if;

  -- Fetch plan
  select seat_count, billing_cycle into v_seats, v_billing
  from public.plans where id = p_plan_id and is_active = true;
  if v_seats is null then
    raise exception 'plan not found or inactive' using errcode = '22023';
  end if;
  if p_seat_count is not null and p_seat_count > 0 then v_seats := p_seat_count; end if;

  -- Owner is the caller for now (org needs owner_user_id NOT NULL).
  -- A separate invite flow can later transfer ownership.
  insert into public.organizations (owner_user_id, name, partner_id, subscription_status, subscription_type)
  values (v_caller, p_org_name, v_partner_id, 'active',
          case when v_billing = 'yearly' then 'yearly' else 'monthly' end)
  returning id into v_org_id;

  -- Compute expiry
  v_expires_at := case when v_billing = 'yearly'
                       then now() + interval '1 year'
                       else now() + interval '1 month'
                  end;

  -- Issue license (license_key auto-generated by table default)
  insert into public.licenses (
    organization_id, partner_id, plan_id, seat_count,
    status, issued_by, expires_at, notes
  )
  values (
    v_org_id, v_partner_id, p_plan_id, v_seats,
    'active', v_caller, v_expires_at, p_notes
  )
  returning id, licenses.license_key into v_license_id, v_license_key;

  -- Audit
  insert into public.audit_log (actor_user, actor_role, action, target_type, target_id, metadata)
  values (v_caller, v_caller_role, 'customer.create', 'organization', v_org_id,
          jsonb_build_object(
            'license_id', v_license_id,
            'plan_id', p_plan_id,
            'seats', v_seats,
            'partner_id', v_partner_id,
            'owner_email', p_owner_email
          ));

  return query select v_org_id, v_license_id, v_license_key, v_expires_at;
end $$;

revoke all on function public.create_customer_with_license(text, uuid, int, text, uuid, text) from public;
grant execute on function public.create_customer_with_license(text, uuid, int, text, uuid, text)
  to authenticated;

-- License-side mutations (suspend/revoke) — same security check, simpler body.
create or replace function public.set_license_status(
  p_license_id  uuid,
  p_status      text,
  p_reason      text default null
)
returns void language plpgsql security definer set search_path = public as $$
declare
  v_caller       uuid := auth.uid();
  v_caller_role  text;
  v_caller_partner uuid;
  v_lic_partner  uuid;
begin
  if v_caller is null then raise exception 'unauthenticated' using errcode = '42501'; end if;
  if p_status not in ('active','suspended','revoked') then
    raise exception 'invalid status' using errcode = '22023';
  end if;

  select app_role, partner_id into v_caller_role, v_caller_partner
  from public.app_users where user_id = v_caller;

  select partner_id into v_lic_partner from public.licenses where id = p_license_id;
  if not found then raise exception 'license not found' using errcode = 'P0002'; end if;

  if v_caller_role = 'partner' then
    if v_lic_partner is null or v_lic_partner <> v_caller_partner then
      raise exception 'forbidden: license not yours' using errcode = '42501';
    end if;
  elsif v_caller_role <> 'super_admin' then
    raise exception 'forbidden' using errcode = '42501';
  end if;

  update public.licenses
    set status = p_status,
        revoked_at = case when p_status = 'revoked' then now() else revoked_at end,
        revoke_reason = case when p_status = 'revoked' then p_reason else revoke_reason end
    where id = p_license_id;

  insert into public.audit_log (actor_user, actor_role, action, target_type, target_id, metadata)
  values (v_caller, v_caller_role, 'license.' || p_status, 'license', p_license_id,
          jsonb_build_object('reason', p_reason));
end $$;

revoke all on function public.set_license_status(uuid, text, text) from public;
grant execute on function public.set_license_status(uuid, text, text) to authenticated;
