-- 0030_notification_recipients.sql
-- Per-org default recipient lists used for credential-request CC (IT team) and
-- offboarding stages. Decisions taken with the user: lists are *defaults*, not
-- enforced; offboarding lets the admin override per-instance.

alter table public.organizations
  add column if not exists it_recipient_emails       text[] not null default '{}',
  add column if not exists hr_recipient_emails       text[] not null default '{}',
  add column if not exists accounts_recipient_emails text[] not null default '{}';

-- Convenience function: get an employee's manager work email (used by
-- credential-request mail TO/CC routing). Returns null if no manager set or
-- the manager has no work_email yet.
create or replace function public.employee_manager_email(p_employee_id uuid)
returns text
language sql
stable
as $$
  select m.work_email
    from public.employees e
    left join public.employees m on m.id = e.manager_id
   where e.id = p_employee_id
$$;

-- Signing key for the public credential-request form session token (HMAC).
-- Generated by the admin once in Admin → Integrations; 32+ chars random hex.
insert into public.integrations (key, value, category, label, description, is_secret) values
  ('CRED_REQUEST_SIGNING_KEY', null, 'security', 'Credentials Request Signing Key',
   'HMAC key for the public credential-request form session token. 32+ chars random.', true),
  ('APP_PUBLIC_URL', null, 'general', 'Public App URL',
   'Origin used in magic links sent by edge functions (e.g. https://ems.wellnessextract.com)', false)
on conflict (key) do nothing;
