-- Default productivity catalogue.
--
-- Until now a new organisation started with an empty productivity_rules table,
-- so every application and site was uncategorised and the productivity figure
-- was computed from nothing. Migration 0118 already fixed one version of this
-- problem ("sabki 50% aa rhi hai" — every agent showing 50%) by excluding
-- uncategorised time from the ratio; the honest consequence was that an org
-- with no rules simply showed no productivity at all.
--
-- This seeds a catalogue of 899 rules so productivity means something on day
-- one, and so an admin has a list to edit rather than a blank page.
--
-- POLICY MODEL (chosen deliberately): everything in this catalogue is
-- productive; anything an employee touches that is NOT here is unproductive.
-- Migration 0134 implements the second half in the scoring functions. That is
-- why there is not a single 'unproductive' row below — under this model an
-- explicit unproductive list would be redundant, and hundreds of rows of
-- blocked domains would obscure the rules that actually carry information.
--
-- The exception is 'neutral', which means "do not count this either way" and
-- is load-bearing here for two groups that would otherwise be scored against
-- the employee unfairly:
--
--   * OS shell and system processes. The lock screen, Start menu, file
--     pickers, the IME host and the window manager all reach the foreground
--     without anyone choosing them.
--   * Browsers themselves, and search engines and webmail. A browser process
--     is a container — what matters is the site, which host rules classify. And
--     a search engine is genuinely both: nearly all research passes through
--     one, as does nearly all time-wasting.
--
-- Rules are seeded per organisation with department = NULL, i.e. as the
-- org-wide default. Admins can retune anything in Admin Portal → Applications,
-- including adding department overrides (see 0129) such as YouTube being
-- productive for a Content team.

CREATE OR REPLACE FUNCTION public.seed_default_productivity_rules(p_org_id uuid)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE
  v_inserted integer;
BEGIN
  WITH catalogue(match_type, pattern, category) AS (
    VALUES
    ('app', 'Code', 'productive'),
    ('app', 'Code - Insiders', 'productive'),
    ('app', 'VSCodium', 'productive'),
    ('app', 'Visual Studio Code', 'productive'),
    ('app', 'devenv', 'productive'),
    ('app', 'Visual Studio', 'productive'),
    ('app', 'Cursor', 'productive'),
    ('app', 'Zed', 'productive'),
    ('app', 'Windsurf', 'productive'),
    ('app', 'Fleet', 'productive'),
    ('app', 'idea64', 'productive'),
    ('app', 'idea', 'productive'),
    ('app', 'IntelliJ IDEA', 'productive'),
    ('app', 'pycharm64', 'productive'),
    ('app', 'pycharm', 'productive'),
    ('app', 'webstorm64', 'productive'),
    ('app', 'WebStorm', 'productive'),
    ('app', 'phpstorm64', 'productive'),
    ('app', 'PhpStorm', 'productive'),
    ('app', 'goland64', 'productive'),
    ('app', 'GoLand', 'productive'),
    ('app', 'rubymine64', 'productive'),
    ('app', 'RubyMine', 'productive'),
    ('app', 'clion64', 'productive'),
    ('app', 'CLion', 'productive'),
    ('app', 'rider64', 'productive'),
    ('app', 'Rider', 'productive'),
    ('app', 'datagrip64', 'productive'),
    ('app', 'DataGrip', 'productive'),
    ('app', 'studio64', 'productive'),
    ('app', 'Android Studio', 'productive'),
    ('app', 'Xcode', 'productive'),
    ('app', 'eclipse', 'productive'),
    ('app', 'netbeans', 'productive'),
    ('app', 'sublime_text', 'productive'),
    ('app', 'Sublime Text', 'productive'),
    ('app', 'notepad++', 'productive'),
    ('app', 'gvim', 'productive'),
    ('app', 'vim', 'productive'),
    ('app', 'nvim', 'productive'),
    ('app', 'Neovim', 'productive'),
    ('app', 'emacs', 'productive'),
    ('app', 'MATLAB', 'productive'),
    ('app', 'RStudio', 'productive'),
    ('app', 'Spyder', 'productive'),
    ('app', 'jupyter-notebook', 'productive'),
    ('app', 'LabVIEW', 'productive'),
    ('app', 'arduino', 'productive'),
    ('app', 'Arduino IDE', 'productive'),
    ('app', 'platformio', 'productive'),
    ('app', 'WindowsTerminal', 'productive'),
    ('app', 'Windows Terminal', 'productive'),
    ('app', 'wt', 'productive'),
    ('app', 'cmd', 'productive'),
    ('app', 'powershell', 'productive'),
    ('app', 'pwsh', 'productive'),
    ('app', 'Terminal', 'productive'),
    ('app', 'iTerm2', 'productive'),
    ('app', 'iTerm', 'productive'),
    ('app', 'Alacritty', 'productive'),
    ('app', 'kitty', 'productive'),
    ('app', 'wezterm', 'productive'),
    ('app', 'Hyper', 'productive'),
    ('app', 'ConEmu', 'productive'),
    ('app', 'Warp', 'productive'),
    ('app', 'Tabby', 'productive'),
    ('app', 'MobaXterm', 'productive'),
    ('app', 'putty', 'productive'),
    ('app', 'WinSCP', 'productive'),
    ('app', 'FileZilla', 'productive'),
    ('app', 'Cyberduck', 'productive'),
    ('app', 'mRemoteNG', 'productive'),
    ('app', 'bash', 'productive'),
    ('app', 'zsh', 'productive'),
    ('app', 'fish', 'productive'),
    ('app', 'DBeaver', 'productive'),
    ('app', 'pgAdmin 4', 'productive'),
    ('app', 'pgadmin4', 'productive'),
    ('app', 'MySQLWorkbench', 'productive'),
    ('app', 'MySQL Workbench', 'productive'),
    ('app', 'SQL Server Management Studio', 'productive'),
    ('app', 'Ssms', 'productive'),
    ('app', 'MongoDB Compass', 'productive'),
    ('app', 'Compass', 'productive'),
    ('app', 'TablePlus', 'productive'),
    ('app', 'RedisInsight', 'productive'),
    ('app', 'SQLiteStudio', 'productive'),
    ('app', 'HeidiSQL', 'productive'),
    ('app', 'Postman', 'productive'),
    ('app', 'Insomnia', 'productive'),
    ('app', 'Bruno', 'productive'),
    ('app', 'SoapUI', 'productive'),
    ('app', 'Fiddler', 'productive'),
    ('app', 'Wireshark', 'productive'),
    ('app', 'Charles', 'productive'),
    ('app', 'Docker Desktop', 'productive'),
    ('app', 'Docker', 'productive'),
    ('app', 'com.docker.docker', 'productive'),
    ('app', 'Rancher Desktop', 'productive'),
    ('app', 'Lens', 'productive'),
    ('app', 'OpenLens', 'productive'),
    ('app', 'k9s', 'productive'),
    ('app', 'minikube', 'productive'),
    ('app', 'VirtualBox', 'productive'),
    ('app', 'VBoxManage', 'productive'),
    ('app', 'vmware', 'productive'),
    ('app', 'VMware Workstation', 'productive'),
    ('app', 'vmconnect', 'productive'),
    ('app', 'Hyper-V Manager', 'productive'),
    ('app', 'Vagrant', 'productive'),
    ('app', 'terraform', 'productive'),
    ('app', 'ansible', 'productive'),
    ('app', 'kubectl', 'productive'),
    ('app', 'helm', 'productive'),
    ('app', 'aws', 'productive'),
    ('app', 'az', 'productive'),
    ('app', 'gcloud', 'productive'),
    ('app', 'GitHubDesktop', 'productive'),
    ('app', 'GitHub Desktop', 'productive'),
    ('app', 'GitKraken', 'productive'),
    ('app', 'Sourcetree', 'productive'),
    ('app', 'Fork', 'productive'),
    ('app', 'Tower', 'productive'),
    ('app', 'TortoiseGit', 'productive'),
    ('app', 'TortoiseSVN', 'productive'),
    ('app', 'git', 'productive'),
    ('app', 'gitk', 'productive'),
    ('app', 'smartgit', 'productive'),
    ('app', 'Beyond Compare', 'productive'),
    ('app', 'BCompare', 'productive'),
    ('app', 'WinMerge', 'productive'),
    ('app', 'meld', 'productive'),
    ('app', 'WINWORD', 'productive'),
    ('app', 'Microsoft Word', 'productive'),
    ('app', 'EXCEL', 'productive'),
    ('app', 'Microsoft Excel', 'productive'),
    ('app', 'POWERPNT', 'productive'),
    ('app', 'Microsoft PowerPoint', 'productive'),
    ('app', 'OUTLOOK', 'productive'),
    ('app', 'Microsoft Outlook', 'productive'),
    ('app', 'ONENOTE', 'productive'),
    ('app', 'Microsoft OneNote', 'productive'),
    ('app', 'MSACCESS', 'productive'),
    ('app', 'Microsoft Access', 'productive'),
    ('app', 'MSPUB', 'productive'),
    ('app', 'Publisher', 'productive'),
    ('app', 'Visio', 'productive'),
    ('app', 'WinProj', 'productive'),
    ('app', 'Microsoft Project', 'productive'),
    ('app', 'Pages', 'productive'),
    ('app', 'Numbers', 'productive'),
    ('app', 'Keynote', 'productive'),
    ('app', 'soffice', 'productive'),
    ('app', 'swriter', 'productive'),
    ('app', 'scalc', 'productive'),
    ('app', 'simpress', 'productive'),
    ('app', 'sbase', 'productive'),
    ('app', 'LibreOffice', 'productive'),
    ('app', 'OpenOffice', 'productive'),
    ('app', 'wps', 'productive'),
    ('app', 'et', 'productive'),
    ('app', 'wpp', 'productive'),
    ('app', 'WPS Office', 'productive'),
    ('app', 'Notion', 'productive'),
    ('app', 'Obsidian', 'productive'),
    ('app', 'Evernote', 'productive'),
    ('app', 'Bear', 'productive'),
    ('app', 'Joplin', 'productive'),
    ('app', 'Logseq', 'productive'),
    ('app', 'Typora', 'productive'),
    ('app', 'Zettlr', 'productive'),
    ('app', 'Standard Notes', 'productive'),
    ('app', 'Anytype', 'productive'),
    ('app', 'Craft', 'productive'),
    ('app', 'Zotero', 'productive'),
    ('app', 'Mendeley', 'productive'),
    ('app', 'EndNote', 'productive'),
    ('app', 'Slack', 'productive'),
    ('app', 'Teams', 'productive'),
    ('app', 'ms-teams', 'productive'),
    ('app', 'Microsoft Teams', 'productive'),
    ('app', 'Zoom', 'productive'),
    ('app', 'Zoom Meetings', 'productive'),
    ('app', 'ZoomMeetings', 'productive'),
    ('app', 'Zoom Workplace', 'productive'),
    ('app', 'CptHost', 'productive'),
    ('app', 'Webex', 'productive'),
    ('app', 'webexmta', 'productive'),
    ('app', 'Cisco Webex Meetings', 'productive'),
    ('app', 'Skype', 'productive'),
    ('app', 'lync', 'productive'),
    ('app', 'GoToMeeting', 'productive'),
    ('app', 'BlueJeans', 'productive'),
    ('app', 'RingCentral', 'productive'),
    ('app', 'Chime', 'productive'),
    ('app', 'Amazon Chime', 'productive'),
    ('app', 'Whereby', 'productive'),
    ('app', 'Around', 'productive'),
    ('app', 'Mattermost', 'productive'),
    ('app', 'Rocket.Chat', 'productive'),
    ('app', 'Chanty', 'productive'),
    ('app', 'Flock', 'productive'),
    ('app', 'Google Chat', 'productive'),
    ('app', 'Jira', 'productive'),
    ('app', 'Linear', 'productive'),
    ('app', 'Asana', 'productive'),
    ('app', 'Trello', 'productive'),
    ('app', 'ClickUp', 'productive'),
    ('app', 'monday.com', 'productive'),
    ('app', 'Monday', 'productive'),
    ('app', 'Basecamp', 'productive'),
    ('app', 'Height', 'productive'),
    ('app', 'Shortcut', 'productive'),
    ('app', 'Wrike', 'productive'),
    ('app', 'Smartsheet', 'productive'),
    ('app', 'Airtable', 'productive'),
    ('app', 'Notion Calendar', 'productive'),
    ('app', 'Todoist', 'productive'),
    ('app', 'TickTick', 'productive'),
    ('app', 'Microsoft To Do', 'productive'),
    ('app', 'OmniFocus', 'productive'),
    ('app', 'Things3', 'productive'),
    ('app', 'Toggl Track', 'productive'),
    ('app', 'Clockify', 'productive'),
    ('app', 'Harvest', 'productive'),
    ('app', 'Jira Software', 'productive'),
    ('app', 'Figma', 'productive'),
    ('app', 'Sketch', 'productive'),
    ('app', 'Adobe XD', 'productive'),
    ('app', 'Photoshop', 'productive'),
    ('app', 'Adobe Photoshop', 'productive'),
    ('app', 'Illustrator', 'productive'),
    ('app', 'Adobe Illustrator', 'productive'),
    ('app', 'InDesign', 'productive'),
    ('app', 'Adobe InDesign', 'productive'),
    ('app', 'AfterFX', 'productive'),
    ('app', 'Adobe After Effects', 'productive'),
    ('app', 'Adobe Premiere Pro', 'productive'),
    ('app', 'Premiere', 'productive'),
    ('app', 'Adobe Lightroom', 'productive'),
    ('app', 'Lightroom', 'productive'),
    ('app', 'Adobe Audition', 'productive'),
    ('app', 'Adobe Animate', 'productive'),
    ('app', 'Adobe Acrobat', 'productive'),
    ('app', 'Acrobat', 'productive'),
    ('app', 'AcroRd32', 'productive'),
    ('app', 'Acrobat Reader', 'productive'),
    ('app', 'Adobe Bridge', 'productive'),
    ('app', 'Substance 3D Painter', 'productive'),
    ('app', 'CorelDRAW', 'productive'),
    ('app', 'Inkscape', 'productive'),
    ('app', 'GIMP', 'productive'),
    ('app', 'Krita', 'productive'),
    ('app', 'Blender', 'productive'),
    ('app', 'Affinity Designer', 'productive'),
    ('app', 'Affinity Photo', 'productive'),
    ('app', 'Affinity Publisher', 'productive'),
    ('app', 'Canva', 'productive'),
    ('app', 'DaVinci Resolve', 'productive'),
    ('app', 'Resolve', 'productive'),
    ('app', 'Final Cut Pro', 'productive'),
    ('app', 'Motion', 'productive'),
    ('app', 'Cinema 4D', 'productive'),
    ('app', 'Maya', 'productive'),
    ('app', '3dsmax', 'productive'),
    ('app', 'ZBrush', 'productive'),
    ('app', 'AutoCAD', 'productive'),
    ('app', 'acad', 'productive'),
    ('app', 'Revit', 'productive'),
    ('app', 'SolidWorks', 'productive'),
    ('app', 'SLDWORKS', 'productive'),
    ('app', 'Fusion360', 'productive'),
    ('app', 'Autodesk Fusion', 'productive'),
    ('app', 'SketchUp', 'productive'),
    ('app', 'Rhino', 'productive'),
    ('app', 'CATIA', 'productive'),
    ('app', 'Creo', 'productive'),
    ('app', 'ArchiCAD', 'productive'),
    ('app', 'Lumion', 'productive'),
    ('app', 'Twinmotion', 'productive'),
    ('app', 'KeyShot', 'productive'),
    ('app', 'QuickBooks', 'productive'),
    ('app', 'qbw32', 'productive'),
    ('app', 'Tally', 'productive'),
    ('app', 'TallyPrime', 'productive'),
    ('app', 'SAP Logon', 'productive'),
    ('app', 'saplogon', 'productive'),
    ('app', 'SAP Business One', 'productive'),
    ('app', 'Oracle', 'productive'),
    ('app', 'sqlplus', 'productive'),
    ('app', 'Xero', 'productive'),
    ('app', 'Zoho Books', 'productive'),
    ('app', 'Sage', 'productive'),
    ('app', 'Busy', 'productive'),
    ('app', 'Marg', 'productive'),
    ('app', 'Odoo', 'productive'),
    ('app', 'NetSuite', 'productive'),
    ('app', 'AnyDesk', 'productive'),
    ('app', 'TeamViewer', 'productive'),
    ('app', 'rustdesk', 'productive'),
    ('app', 'mstsc', 'productive'),
    ('app', 'Remote Desktop Connection', 'productive'),
    ('app', 'Chrome Remote Desktop', 'productive'),
    ('app', 'VNC Viewer', 'productive'),
    ('app', 'RealVNC', 'productive'),
    ('app', 'Splashtop', 'productive'),
    ('app', 'ScreenConnect', 'productive'),
    ('app', 'LogMeIn', 'productive'),
    ('app', 'Dameware', 'productive'),
    ('app', 'mmc', 'productive'),
    ('app', 'regedit', 'productive'),
    ('app', 'services', 'productive'),
    ('app', 'eventvwr', 'productive'),
    ('app', 'perfmon', 'productive'),
    ('app', 'compmgmt', 'productive'),
    ('app', 'gpedit', 'productive'),
    ('app', 'secpol', 'productive'),
    ('app', 'lusrmgr', 'productive'),
    ('app', 'dsa', 'productive'),
    ('app', 'Active Directory Users and Computers', 'productive'),
    ('app', 'Group Policy Management', 'productive'),
    ('app', 'Veeam', 'productive'),
    ('app', 'Acronis', 'productive'),
    ('app', 'KeePass', 'productive'),
    ('app', 'KeePassXC', 'productive'),
    ('app', '1Password', 'productive'),
    ('app', 'Bitwarden', 'productive'),
    ('app', 'LastPass', 'productive'),
    ('app', 'Dashlane', 'productive'),
    ('app', 'Nessus', 'productive'),
    ('app', 'Burp Suite', 'productive'),
    ('app', 'burpsuite', 'productive'),
    ('app', 'nmap', 'productive'),
    ('app', 'Zenmap', 'productive'),
    ('app', 'Metasploit', 'productive'),
    ('app', 'Selenium IDE', 'productive'),
    ('app', 'Cypress', 'productive'),
    ('app', 'Playwright', 'productive'),
    ('app', 'JMeter', 'productive'),
    ('app', 'Katalon Studio', 'productive'),
    ('app', 'TestRail', 'productive'),
    ('app', 'BrowserStack', 'productive'),
    ('app', 'Snagit', 'productive'),
    ('app', 'Camtasia', 'productive'),
    ('app', 'OBS Studio', 'productive'),
    ('app', 'obs64', 'productive'),
    ('app', 'ShareX', 'productive'),
    ('app', 'Greenshot', 'productive'),
    ('app', 'Loom', 'productive'),
    ('app', 'Screenpresso', 'productive'),
    ('app', 'explorer', 'neutral'),
    ('app', 'Finder', 'neutral'),
    ('app', 'LockApp', 'neutral'),
    ('app', 'LogonUI', 'neutral'),
    ('app', 'ShellHost', 'neutral'),
    ('app', 'ShellExperienceHost', 'neutral'),
    ('app', 'StartMenuExperienceHost', 'neutral'),
    ('app', 'SearchHost', 'neutral'),
    ('app', 'SearchApp', 'neutral'),
    ('app', 'SearchUI', 'neutral'),
    ('app', 'TextInputHost', 'neutral'),
    ('app', 'ctfmon', 'neutral'),
    ('app', 'ApplicationFrameHost', 'neutral'),
    ('app', 'dwm', 'neutral'),
    ('app', 'sihost', 'neutral'),
    ('app', 'RuntimeBroker', 'neutral'),
    ('app', 'PickerHost', 'neutral'),
    ('app', 'DataExchangeHost', 'neutral'),
    ('app', 'dllhost', 'neutral'),
    ('app', 'rundll32', 'neutral'),
    ('app', 'taskhostw', 'neutral'),
    ('app', 'backgroundTaskHost', 'neutral'),
    ('app', 'SystemSettings', 'neutral'),
    ('app', 'ImmersiveControlPanel', 'neutral'),
    ('app', 'control', 'neutral'),
    ('app', 'Taskmgr', 'neutral'),
    ('app', 'Task Manager', 'neutral'),
    ('app', 'resmon', 'neutral'),
    ('app', 'SecurityHealthSystray', 'neutral'),
    ('app', 'SecurityHealthHost', 'neutral'),
    ('app', 'Widgets', 'neutral'),
    ('app', 'WidgetBoard', 'neutral'),
    ('app', 'ScreenClippingHost', 'neutral'),
    ('app', 'SnippingTool', 'neutral'),
    ('app', 'ScreenSketch', 'neutral'),
    ('app', 'msedgewebview2', 'neutral'),
    ('app', 'WWAHost', 'neutral'),
    ('app', 'smartscreen', 'neutral'),
    ('app', 'UserOOBEBroker', 'neutral'),
    ('app', 'CredentialUIBroker', 'neutral'),
    ('app', 'SystemUIServer', 'neutral'),
    ('app', 'Dock', 'neutral'),
    ('app', 'loginwindow', 'neutral'),
    ('app', 'WindowServer', 'neutral'),
    ('app', 'Spotlight', 'neutral'),
    ('app', 'gnome-shell', 'neutral'),
    ('app', 'plasmashell', 'neutral'),
    ('app', 'xfdesktop', 'neutral'),
    ('app', 'nautilus', 'neutral'),
    ('app', 'chrome', 'neutral'),
    ('app', 'Google Chrome', 'neutral'),
    ('app', 'msedge', 'neutral'),
    ('app', 'Microsoft Edge', 'neutral'),
    ('app', 'firefox', 'neutral'),
    ('app', 'Mozilla Firefox', 'neutral'),
    ('app', 'Safari', 'neutral'),
    ('app', 'brave', 'neutral'),
    ('app', 'Brave Browser', 'neutral'),
    ('app', 'opera', 'neutral'),
    ('app', 'vivaldi', 'neutral'),
    ('app', 'Arc', 'neutral'),
    ('app', 'chromium', 'neutral'),
    ('app', 'iexplore', 'neutral'),
    ('app', 'wellness-extract-agent', 'neutral'),
    ('app', 'Security Assistant', 'neutral'),
    ('host', 'github.com', 'productive'),
    ('host', 'gitlab.com', 'productive'),
    ('host', 'bitbucket.org', 'productive'),
    ('host', 'dev.azure.com', 'productive'),
    ('host', 'visualstudio.com', 'productive'),
    ('host', 'sourceforge.net', 'productive'),
    ('host', 'codeberg.org', 'productive'),
    ('host', 'gitea.com', 'productive'),
    ('host', 'npmjs.com', 'productive'),
    ('host', 'pypi.org', 'productive'),
    ('host', 'crates.io', 'productive'),
    ('host', 'rubygems.org', 'productive'),
    ('host', 'packagist.org', 'productive'),
    ('host', 'nuget.org', 'productive'),
    ('host', 'mvnrepository.com', 'productive'),
    ('host', 'maven.apache.org', 'productive'),
    ('host', 'hub.docker.com', 'productive'),
    ('host', 'quay.io', 'productive'),
    ('host', 'artifacthub.io', 'productive'),
    ('host', 'gradle.org', 'productive'),
    ('host', 'cocoapods.org', 'productive'),
    ('host', 'stackoverflow.com', 'productive'),
    ('host', 'stackexchange.com', 'productive'),
    ('host', 'serverfault.com', 'productive'),
    ('host', 'superuser.com', 'productive'),
    ('host', 'askubuntu.com', 'productive'),
    ('host', 'developer.mozilla.org', 'productive'),
    ('host', 'learn.microsoft.com', 'productive'),
    ('host', 'docs.microsoft.com', 'productive'),
    ('host', 'devdocs.io', 'productive'),
    ('host', 'readthedocs.io', 'productive'),
    ('host', 'readthedocs.org', 'productive'),
    ('host', 'w3schools.com', 'productive'),
    ('host', 'geeksforgeeks.org', 'productive'),
    ('host', 'tutorialspoint.com', 'productive'),
    ('host', 'freecodecamp.org', 'productive'),
    ('host', 'digitalocean.com', 'productive'),
    ('host', 'baeldung.com', 'productive'),
    ('host', 'realpython.com', 'productive'),
    ('host', 'css-tricks.com', 'productive'),
    ('host', 'smashingmagazine.com', 'productive'),
    ('host', 'web.dev', 'productive'),
    ('host', 'caniuse.com', 'productive'),
    ('host', 'regex101.com', 'productive'),
    ('host', 'regexr.com', 'productive'),
    ('host', 'explainshell.com', 'productive'),
    ('host', 'devhints.io', 'productive'),
    ('host', 'roadmap.sh', 'productive'),
    ('host', 'refactoring.guru', 'productive'),
    ('host', 'martinfowler.com', 'productive'),
    ('host', 'leetcode.com', 'productive'),
    ('host', 'hackerrank.com', 'productive'),
    ('host', 'codewars.com', 'productive'),
    ('host', 'exercism.org', 'productive'),
    ('host', 'codeforces.com', 'productive'),
    ('host', 'topcoder.com', 'productive'),
    ('host', 'interviewbit.com', 'productive'),
    ('host', 'neetcode.io', 'productive'),
    ('host', 'coursera.org', 'productive'),
    ('host', 'udemy.com', 'productive'),
    ('host', 'edx.org', 'productive'),
    ('host', 'pluralsight.com', 'productive'),
    ('host', 'linkedin.com', 'productive'),
    ('host', 'egghead.io', 'productive'),
    ('host', 'frontendmasters.com', 'productive'),
    ('host', 'oreilly.com', 'productive'),
    ('host', 'datacamp.com', 'productive'),
    ('host', 'kaggle.com', 'productive'),
    ('host', 'huggingface.co', 'productive'),
    ('host', 'paperswithcode.com', 'productive'),
    ('host', 'arxiv.org', 'productive'),
    ('host', 'scholar.google.com', 'productive'),
    ('host', 'ieee.org', 'productive'),
    ('host', 'acm.org', 'productive'),
    ('host', 'python.org', 'productive'),
    ('host', 'nodejs.org', 'productive'),
    ('host', 'typescriptlang.org', 'productive'),
    ('host', 'rust-lang.org', 'productive'),
    ('host', 'go.dev', 'productive'),
    ('host', 'golang.org', 'productive'),
    ('host', 'kotlinlang.org', 'productive'),
    ('host', 'swift.org', 'productive'),
    ('host', 'php.net', 'productive'),
    ('host', 'ruby-lang.org', 'productive'),
    ('host', 'scala-lang.org', 'productive'),
    ('host', 'dart.dev', 'productive'),
    ('host', 'java.com', 'productive'),
    ('host', 'oracle.com', 'productive'),
    ('host', 'dotnet.microsoft.com', 'productive'),
    ('host', 'react.dev', 'productive'),
    ('host', 'reactjs.org', 'productive'),
    ('host', 'vuejs.org', 'productive'),
    ('host', 'angular.io', 'productive'),
    ('host', 'angular.dev', 'productive'),
    ('host', 'svelte.dev', 'productive'),
    ('host', 'solidjs.com', 'productive'),
    ('host', 'nextjs.org', 'productive'),
    ('host', 'nuxt.com', 'productive'),
    ('host', 'remix.run', 'productive'),
    ('host', 'astro.build', 'productive'),
    ('host', 'vitejs.dev', 'productive'),
    ('host', 'webpack.js.org', 'productive'),
    ('host', 'tailwindcss.com', 'productive'),
    ('host', 'getbootstrap.com', 'productive'),
    ('host', 'sass-lang.com', 'productive'),
    ('host', 'mui.com', 'productive'),
    ('host', 'chakra-ui.com', 'productive'),
    ('host', 'ant.design', 'productive'),
    ('host', 'shadcn.com', 'productive'),
    ('host', 'laravel.com', 'productive'),
    ('host', 'symfony.com', 'productive'),
    ('host', 'djangoproject.com', 'productive'),
    ('host', 'palletsprojects.com', 'productive'),
    ('host', 'fastapi.tiangolo.com', 'productive'),
    ('host', 'spring.io', 'productive'),
    ('host', 'expressjs.com', 'productive'),
    ('host', 'nestjs.com', 'productive'),
    ('host', 'rubyonrails.org', 'productive'),
    ('host', 'flutter.dev', 'productive'),
    ('host', 'reactnative.dev', 'productive'),
    ('host', 'developer.android.com', 'productive'),
    ('host', 'developer.apple.com', 'productive'),
    ('host', 'unity.com', 'productive'),
    ('host', 'unrealengine.com', 'productive'),
    ('host', 'godotengine.org', 'productive'),
    ('host', 'electronjs.org', 'productive'),
    ('host', 'tauri.app', 'productive'),
    ('host', 'graphql.org', 'productive'),
    ('host', 'trpc.io', 'productive'),
    ('host', 'prisma.io', 'productive'),
    ('host', 'drizzle.team', 'productive'),
    ('host', 'sequelize.org', 'productive'),
    ('host', 'typeorm.io', 'productive'),
    ('host', 'aws.amazon.com', 'productive'),
    ('host', 'amazonaws.com', 'productive'),
    ('host', 'portal.azure.com', 'productive'),
    ('host', 'azure.microsoft.com', 'productive'),
    ('host', 'cloud.google.com', 'productive'),
    ('host', 'gcp.gg', 'productive'),
    ('host', 'cloudflare.com', 'productive'),
    ('host', 'vercel.com', 'productive'),
    ('host', 'netlify.com', 'productive'),
    ('host', 'heroku.com', 'productive'),
    ('host', 'render.com', 'productive'),
    ('host', 'railway.app', 'productive'),
    ('host', 'fly.io', 'productive'),
    ('host', 'supabase.com', 'productive'),
    ('host', 'supabase.io', 'productive'),
    ('host', 'firebase.google.com', 'productive'),
    ('host', 'planetscale.com', 'productive'),
    ('host', 'neon.tech', 'productive'),
    ('host', 'mongodb.com', 'productive'),
    ('host', 'redis.io', 'productive'),
    ('host', 'postgresql.org', 'productive'),
    ('host', 'mysql.com', 'productive'),
    ('host', 'sqlite.org', 'productive'),
    ('host', 'elastic.co', 'productive'),
    ('host', 'clickhouse.com', 'productive'),
    ('host', 'snowflake.com', 'productive'),
    ('host', 'databricks.com', 'productive'),
    ('host', 'hashicorp.com', 'productive'),
    ('host', 'terraform.io', 'productive'),
    ('host', 'kubernetes.io', 'productive'),
    ('host', 'docker.com', 'productive'),
    ('host', 'helm.sh', 'productive'),
    ('host', 'ansible.com', 'productive'),
    ('host', 'jenkins.io', 'productive'),
    ('host', 'circleci.com', 'productive'),
    ('host', 'travis-ci.com', 'productive'),
    ('host', 'teamcity.com', 'productive'),
    ('host', 'sonarsource.com', 'productive'),
    ('host', 'sonarqube.org', 'productive'),
    ('host', 'grafana.com', 'productive'),
    ('host', 'prometheus.io', 'productive'),
    ('host', 'datadoghq.com', 'productive'),
    ('host', 'newrelic.com', 'productive'),
    ('host', 'sentry.io', 'productive'),
    ('host', 'rollbar.com', 'productive'),
    ('host', 'bugsnag.com', 'productive'),
    ('host', 'pagerduty.com', 'productive'),
    ('host', 'opsgenie.com', 'productive'),
    ('host', 'statuspage.io', 'productive'),
    ('host', 'uptimerobot.com', 'productive'),
    ('host', 'betterstack.com', 'productive'),
    ('host', 'sumologic.com', 'productive'),
    ('host', 'splunk.com', 'productive'),
    ('host', 'nginx.org', 'productive'),
    ('host', 'apache.org', 'productive'),
    ('host', 'letsencrypt.org', 'productive'),
    ('host', 'ssllabs.com', 'productive'),
    ('host', 'namecheap.com', 'productive'),
    ('host', 'godaddy.com', 'productive'),
    ('host', 'route53.amazonaws.com', 'productive'),
    ('host', 'codepen.io', 'productive'),
    ('host', 'jsfiddle.net', 'productive'),
    ('host', 'codesandbox.io', 'productive'),
    ('host', 'replit.com', 'productive'),
    ('host', 'stackblitz.com', 'productive'),
    ('host', 'jsonformatter.org', 'productive'),
    ('host', 'jsonlint.com', 'productive'),
    ('host', 'jwt.io', 'productive'),
    ('host', 'base64decode.org', 'productive'),
    ('host', 'urlencoder.org', 'productive'),
    ('host', 'diffchecker.com', 'productive'),
    ('host', 'gitignore.io', 'productive'),
    ('host', 'crontab.guru', 'productive'),
    ('host', 'transform.tools', 'productive'),
    ('host', 'quicktype.io', 'productive'),
    ('host', 'mockaroo.com', 'productive'),
    ('host', 'swagger.io', 'productive'),
    ('host', 'postman.com', 'productive'),
    ('host', 'hoppscotch.io', 'productive'),
    ('host', 'apidog.com', 'productive'),
    ('host', 'requestbin.com', 'productive'),
    ('host', 'webhook.site', 'productive'),
    ('host', 'ngrok.com', 'productive'),
    ('host', 'localtunnel.me', 'productive'),
    ('host', 'shields.io', 'productive'),
    ('host', 'carbon.now.sh', 'productive'),
    ('host', 'tldraw.com', 'productive'),
    ('host', 'office.com', 'productive'),
    ('host', 'office365.com', 'productive'),
    ('host', 'microsoft365.com', 'productive'),
    ('host', 'sharepoint.com', 'productive'),
    ('host', 'onedrive.live.com', 'productive'),
    ('host', 'live.com', 'productive'),
    ('host', 'docs.google.com', 'productive'),
    ('host', 'sheets.google.com', 'productive'),
    ('host', 'slides.google.com', 'productive'),
    ('host', 'drive.google.com', 'productive'),
    ('host', 'forms.google.com', 'productive'),
    ('host', 'calendar.google.com', 'productive'),
    ('host', 'keep.google.com', 'productive'),
    ('host', 'sites.google.com', 'productive'),
    ('host', 'dropbox.com', 'productive'),
    ('host', 'box.com', 'productive'),
    ('host', 'icloud.com', 'productive'),
    ('host', 'sync.com', 'productive'),
    ('host', 'pcloud.com', 'productive'),
    ('host', 'notion.so', 'productive'),
    ('host', 'obsidian.md', 'productive'),
    ('host', 'evernote.com', 'productive'),
    ('host', 'coda.io', 'productive'),
    ('host', 'airtable.com', 'productive'),
    ('host', 'smartsheet.com', 'productive'),
    ('host', 'zoho.com', 'productive'),
    ('host', 'quip.com', 'productive'),
    ('host', 'slite.com', 'productive'),
    ('host', 'nuclino.com', 'productive'),
    ('host', 'gitbook.com', 'productive'),
    ('host', 'confluence.atlassian.com', 'productive'),
    ('host', 'atlassian.net', 'productive'),
    ('host', 'slack.com', 'productive'),
    ('host', 'teams.microsoft.com', 'productive'),
    ('host', 'teams.live.com', 'productive'),
    ('host', 'zoom.us', 'productive'),
    ('host', 'webex.com', 'productive'),
    ('host', 'meet.google.com', 'productive'),
    ('host', 'chat.google.com', 'productive'),
    ('host', 'whereby.com', 'productive'),
    ('host', 'gather.town', 'productive'),
    ('host', 'around.co', 'productive'),
    ('host', 'mattermost.com', 'productive'),
    ('host', 'rocket.chat', 'productive'),
    ('host', 'discord.com', 'productive'),
    ('host', 'skype.com', 'productive'),
    ('host', 'ringcentral.com', 'productive'),
    ('host', 'dialpad.com', 'productive'),
    ('host', 'twilio.com', 'productive'),
    ('host', 'sendbird.com', 'productive'),
    ('host', 'getstream.io', 'productive'),
    ('host', 'jira.com', 'productive'),
    ('host', 'linear.app', 'productive'),
    ('host', 'asana.com', 'productive'),
    ('host', 'trello.com', 'productive'),
    ('host', 'clickup.com', 'productive'),
    ('host', 'monday.com', 'productive'),
    ('host', 'basecamp.com', 'productive'),
    ('host', 'shortcut.com', 'productive'),
    ('host', 'height.app', 'productive'),
    ('host', 'wrike.com', 'productive'),
    ('host', 'teamwork.com', 'productive'),
    ('host', 'productboard.com', 'productive'),
    ('host', 'aha.io', 'productive'),
    ('host', 'miro.com', 'productive'),
    ('host', 'figma.com', 'productive'),
    ('host', 'lucidchart.com', 'productive'),
    ('host', 'lucid.app', 'productive'),
    ('host', 'draw.io', 'productive'),
    ('host', 'diagrams.net', 'productive'),
    ('host', 'excalidraw.com', 'productive'),
    ('host', 'whimsical.com', 'productive'),
    ('host', 'mural.co', 'productive'),
    ('host', 'servicenow.com', 'productive'),
    ('host', 'zendesk.com', 'productive'),
    ('host', 'freshdesk.com', 'productive'),
    ('host', 'freshservice.com', 'productive'),
    ('host', 'helpscout.com', 'productive'),
    ('host', 'intercom.com', 'productive'),
    ('host', 'front.app', 'productive'),
    ('host', 'crisp.chat', 'productive'),
    ('host', 'tawk.to', 'productive'),
    ('host', 'happyfox.com', 'productive'),
    ('host', 'jitbit.com', 'productive'),
    ('host', 'osticket.com', 'productive'),
    ('host', 'spiceworks.com', 'productive'),
    ('host', 'canva.com', 'productive'),
    ('host', 'adobe.com', 'productive'),
    ('host', 'behance.net', 'productive'),
    ('host', 'dribbble.com', 'productive'),
    ('host', 'unsplash.com', 'productive'),
    ('host', 'pexels.com', 'productive'),
    ('host', 'pixabay.com', 'productive'),
    ('host', 'freepik.com', 'productive'),
    ('host', 'flaticon.com', 'productive'),
    ('host', 'fontawesome.com', 'productive'),
    ('host', 'fonts.google.com', 'productive'),
    ('host', 'coolors.co', 'productive'),
    ('host', 'colorhunt.co', 'productive'),
    ('host', 'sketch.com', 'productive'),
    ('host', 'framer.com', 'productive'),
    ('host', 'webflow.com', 'productive'),
    ('host', 'penpot.app', 'productive'),
    ('host', 'iconify.design', 'productive'),
    ('host', 'thenounproject.com', 'productive'),
    ('host', 'storyset.com', 'productive'),
    ('host', 'undraw.co', 'productive'),
    ('host', 'lottiefiles.com', 'productive'),
    ('host', 'remixicon.com', 'productive'),
    ('host', 'heroicons.com', 'productive'),
    ('host', 'lucide.dev', 'productive'),
    ('host', 'shapefactory.co', 'productive'),
    ('host', 'tinypng.com', 'productive'),
    ('host', 'squoosh.app', 'productive'),
    ('host', 'removebg.com', 'productive'),
    ('host', 'remove.bg', 'productive'),
    ('host', 'salesforce.com', 'productive'),
    ('host', 'force.com', 'productive'),
    ('host', 'hubspot.com', 'productive'),
    ('host', 'pipedrive.com', 'productive'),
    ('host', 'zohocrm.com', 'productive'),
    ('host', 'freshworks.com', 'productive'),
    ('host', 'freshsales.io', 'productive'),
    ('host', 'close.com', 'productive'),
    ('host', 'copper.com', 'productive'),
    ('host', 'insightly.com', 'productive'),
    ('host', 'sugarcrm.com', 'productive'),
    ('host', 'outreach.io', 'productive'),
    ('host', 'salesloft.com', 'productive'),
    ('host', 'apollo.io', 'productive'),
    ('host', 'gong.io', 'productive'),
    ('host', 'chorus.ai', 'productive'),
    ('host', 'lusha.com', 'productive'),
    ('host', 'zoominfo.com', 'productive'),
    ('host', 'clearbit.com', 'productive'),
    ('host', 'hunter.io', 'productive'),
    ('host', 'snov.io', 'productive'),
    ('host', 'lemlist.com', 'productive'),
    ('host', 'mailchimp.com', 'productive'),
    ('host', 'sendgrid.com', 'productive'),
    ('host', 'klaviyo.com', 'productive'),
    ('host', 'activecampaign.com', 'productive'),
    ('host', 'marketo.com', 'productive'),
    ('host', 'pardot.com', 'productive'),
    ('host', 'brevo.com', 'productive'),
    ('host', 'sendinblue.com', 'productive'),
    ('host', 'constantcontact.com', 'productive'),
    ('host', 'convertkit.com', 'productive'),
    ('host', 'customer.io', 'productive'),
    ('host', 'semrush.com', 'productive'),
    ('host', 'ahrefs.com', 'productive'),
    ('host', 'moz.com', 'productive'),
    ('host', 'similarweb.com', 'productive'),
    ('host', 'ubersuggest.com', 'productive'),
    ('host', 'analytics.google.com', 'productive'),
    ('host', 'ads.google.com', 'productive'),
    ('host', 'tagmanager.google.com', 'productive'),
    ('host', 'search.google.com', 'productive'),
    ('host', 'business.facebook.com', 'productive'),
    ('host', 'ads.tiktok.com', 'productive'),
    ('host', 'ads.linkedin.com', 'productive'),
    ('host', 'mixpanel.com', 'productive'),
    ('host', 'amplitude.com', 'productive'),
    ('host', 'hotjar.com', 'productive'),
    ('host', 'posthog.com', 'productive'),
    ('host', 'segment.com', 'productive'),
    ('host', 'looker.com', 'productive'),
    ('host', 'tableau.com', 'productive'),
    ('host', 'powerbi.microsoft.com', 'productive'),
    ('host', 'metabase.com', 'productive'),
    ('host', 'hootsuite.com', 'productive'),
    ('host', 'buffer.com', 'productive'),
    ('host', 'sproutsocial.com', 'productive'),
    ('host', 'later.com', 'productive'),
    ('host', 'sprinklr.com', 'productive'),
    ('host', 'quickbooks.intuit.com', 'productive'),
    ('host', 'intuit.com', 'productive'),
    ('host', 'xero.com', 'productive'),
    ('host', 'sage.com', 'productive'),
    ('host', 'freshbooks.com', 'productive'),
    ('host', 'wave.com', 'productive'),
    ('host', 'tallysolutions.com', 'productive'),
    ('host', 'sap.com', 'productive'),
    ('host', 'netsuite.com', 'productive'),
    ('host', 'odoo.com', 'productive'),
    ('host', 'zoho.in', 'productive'),
    ('host', 'stripe.com', 'productive'),
    ('host', 'razorpay.com', 'productive'),
    ('host', 'payu.in', 'productive'),
    ('host', 'paypal.com', 'productive'),
    ('host', 'wise.com', 'productive'),
    ('host', 'brex.com', 'productive'),
    ('host', 'ramp.com', 'productive'),
    ('host', 'expensify.com', 'productive'),
    ('host', 'navan.com', 'productive'),
    ('host', 'bill.com', 'productive'),
    ('host', 'avalara.com', 'productive'),
    ('host', 'workday.com', 'productive'),
    ('host', 'bamboohr.com', 'productive'),
    ('host', 'gusto.com', 'productive'),
    ('host', 'rippling.com', 'productive'),
    ('host', 'deel.com', 'productive'),
    ('host', 'remote.com', 'productive'),
    ('host', 'keka.com', 'productive'),
    ('host', 'darwinbox.com', 'productive'),
    ('host', 'zohopeople.com', 'productive'),
    ('host', 'greenhouse.io', 'productive'),
    ('host', 'lever.co', 'productive'),
    ('host', 'workable.com', 'productive'),
    ('host', 'smartrecruiters.com', 'productive'),
    ('host', 'naukri.com', 'productive'),
    ('host', 'indeed.com', 'productive'),
    ('host', 'glassdoor.com', 'productive'),
    ('host', 'docusign.com', 'productive'),
    ('host', 'pandadoc.com', 'productive'),
    ('host', 'ironcladapp.com', 'productive'),
    ('host', 'clio.com', 'productive'),
    ('host', 'lawinsider.com', 'productive'),
    ('host', 'gst.gov.in', 'productive'),
    ('host', 'incometax.gov.in', 'productive'),
    ('host', 'mca.gov.in', 'productive'),
    ('host', 'epfindia.gov.in', 'productive'),
    ('host', 'esic.gov.in', 'productive'),
    ('host', 'tin-nsdl.com', 'productive'),
    ('host', 'irs.gov', 'productive'),
    ('host', 'gov.uk', 'productive'),
    ('host', 'chatgpt.com', 'productive'),
    ('host', 'openai.com', 'productive'),
    ('host', 'claude.ai', 'productive'),
    ('host', 'anthropic.com', 'productive'),
    ('host', 'gemini.google.com', 'productive'),
    ('host', 'copilot.microsoft.com', 'productive'),
    ('host', 'github.dev', 'productive'),
    ('host', 'perplexity.ai', 'productive'),
    ('host', 'poe.com', 'productive'),
    ('host', 'mistral.ai', 'productive'),
    ('host', 'cohere.com', 'productive'),
    ('host', 'v0.dev', 'productive'),
    ('host', 'bolt.new', 'productive'),
    ('host', 'lovable.dev', 'productive'),
    ('host', 'cursor.com', 'productive'),
    ('host', 'codeium.com', 'productive'),
    ('host', 'tabnine.com', 'productive'),
    ('host', 'google.com', 'neutral'),
    ('host', 'www.google.com', 'neutral'),
    ('host', 'bing.com', 'neutral'),
    ('host', 'duckduckgo.com', 'neutral'),
    ('host', 'search.brave.com', 'neutral'),
    ('host', 'ecosia.org', 'neutral'),
    ('host', 'startpage.com', 'neutral'),
    ('host', 'yandex.com', 'neutral'),
    ('host', 'mail.google.com', 'neutral'),
    ('host', 'outlook.office.com', 'neutral'),
    ('host', 'outlook.office365.com', 'neutral'),
    ('host', 'outlook.live.com', 'neutral'),
    ('host', 'mail.yahoo.com', 'neutral'),
    ('host', 'mail.proton.me', 'neutral'),
    ('host', 'zoho.com/mail', 'neutral'),
    ('host', 'translate.google.com', 'neutral'),
    ('host', 'wikipedia.org', 'neutral'),
    ('host', 'wikimedia.org', 'neutral'),
    ('host', 'localhost', 'neutral'),
    ('host', '127.0.0.1', 'neutral'),
    ('host', '0.0.0.0', 'neutral')
  ),
  ins AS (
    INSERT INTO public.productivity_rules (org_id, match_type, pattern, category, department)
    SELECT p_org_id, c.match_type, c.pattern, c.category, NULL
    FROM catalogue c
    -- Never overwrite a decision an admin has already made. The unique key is
    -- (org_id, match_type, pattern, department) with NULLS NOT DISTINCT, so a
    -- hand-edited rule for the same pattern simply wins.
    ON CONFLICT (org_id, match_type, pattern, department) DO NOTHING
    RETURNING 1
  )
  SELECT count(*) INTO v_inserted FROM ins;
  RETURN v_inserted;
END
$fn$;

COMMENT ON FUNCTION public.seed_default_productivity_rules(uuid) IS
  'Seeds the default productive/neutral catalogue for one organisation. '
  'Idempotent and non-destructive: existing rules for the same pattern are '
  'left untouched, so it is safe to re-run after the catalogue grows.';

-- Backfill every organisation that exists today.
DO $do$
DECLARE r record; n integer; total integer := 0;
BEGIN
  FOR r IN SELECT id FROM public.organizations LOOP
    SELECT public.seed_default_productivity_rules(r.id) INTO n;
    total := total + n;
  END LOOP;
  RAISE NOTICE 'seeded % default productivity rules across all organisations', total;
END $do$;

-- And every organisation created from now on, so a new customer is never left
-- with a blank ruleset. AFTER INSERT so a failure here cannot roll back the
-- signup itself.
CREATE OR REPLACE FUNCTION public.tg_seed_org_productivity_rules()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $tg$
BEGIN
  PERFORM public.seed_default_productivity_rules(NEW.id);
  RETURN NULL;
EXCEPTION WHEN OTHERS THEN
  -- Seeding defaults is a convenience, not a precondition for having an
  -- account. Log and carry on rather than failing organisation creation.
  RAISE WARNING 'could not seed default productivity rules for org %: %', NEW.id, SQLERRM;
  RETURN NULL;
END
$tg$;

DROP TRIGGER IF EXISTS trg_seed_org_productivity_rules ON public.organizations;
CREATE TRIGGER trg_seed_org_productivity_rules
  AFTER INSERT ON public.organizations
  FOR EACH ROW EXECUTE FUNCTION public.tg_seed_org_productivity_rules();

NOTIFY pgrst, 'reload schema';
