-- Catalogue extension: AI, design and marketing tooling.
--
-- 0133 covered engineering, office and general SaaS well but was thin on the
-- work marketing, design and content teams actually do — and since 0134 made
-- anything uncatalogued UNPRODUCTIVE, a thin catalogue is not merely incomplete,
-- it actively misreports those teams. A designer in Spline or a marketer in
-- Braze was being scored the same as someone on a piracy site.
--
-- 470 rules added across generative AI, design tooling, martech, analytics, SEO,
-- social management, CRO and e-commerce back office, as both applications and
-- websites.
--
-- ONE DELIBERATE CHOICE WORTH READING. The social platforms are seeded as
-- NEUTRAL, not productive:
--
--   facebook.com  instagram.com  x.com  linkedin.com  tiktok.com  youtube.com
--   reddit.com    whatsapp.com   telegram  quora.com   medium.com
--
-- They are genuinely part of a marketing job and equally where time disappears,
-- and nothing in an activity log distinguishes the two. Marking them productive
-- would make scrolling any feed count as work; marking them unproductive would
-- punish the social team for doing theirs. Neutral is excluded from the ratio
-- entirely, which is the only honest option.
--
-- The BUSINESS surfaces are productive, because reaching them requires intent:
-- business.facebook.com, adsmanager.facebook.com, business.instagram.com,
-- creator.instagram.com, business.meta.com, studio.youtube.com,
-- business.tiktok.com. Host rules match subdomains but the parent domains above
-- are seeded explicitly as neutral, and an exact rule outranks a suffix match
-- (0137), so the two coexist correctly: the ads manager scores as work while the
-- consumer feed does not.

CREATE OR REPLACE FUNCTION public.seed_ai_design_martech_rules(p_org_id uuid)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $fn$
DECLARE v_inserted integer;
BEGIN
  WITH catalogue(match_type, pattern, category) AS (
    VALUES
    ('host', 'heygen.com', 'productive'),
    ('host', 'synthesia.io', 'productive'),
    ('host', 'elevenlabs.io', 'productive'),
    ('host', 'runwayml.com', 'productive'),
    ('host', 'runway.com', 'productive'),
    ('host', 'pika.art', 'productive'),
    ('host', 'lumalabs.ai', 'productive'),
    ('host', 'kling.ai', 'productive'),
    ('host', 'hailuoai.video', 'productive'),
    ('host', 'haiper.ai', 'productive'),
    ('host', 'genmo.ai', 'productive'),
    ('host', 'moonvalley.com', 'productive'),
    ('host', 'higgsfield.ai', 'productive'),
    ('host', 'topazlabs.com', 'productive'),
    ('host', 'descript.com', 'productive'),
    ('host', 'opus.pro', 'productive'),
    ('host', 'submagic.co', 'productive'),
    ('host', 'veed.io', 'productive'),
    ('host', 'kapwing.com', 'productive'),
    ('host', 'invideo.io', 'productive'),
    ('host', 'pictory.ai', 'productive'),
    ('host', 'fliki.ai', 'productive'),
    ('host', 'murf.ai', 'productive'),
    ('host', 'play.ht', 'productive'),
    ('host', 'resemble.ai', 'productive'),
    ('host', 'speechify.com', 'productive'),
    ('host', 'wellsaidlabs.com', 'productive'),
    ('host', 'papercup.com', 'productive'),
    ('host', 'captions.ai', 'productive'),
    ('host', 'argil.ai', 'productive'),
    ('host', 'colossyan', 'productive'),
    ('host', 'deepbrain.io', 'productive'),
    ('host', 'midjourney.com', 'productive'),
    ('host', 'leonardo.ai', 'productive'),
    ('host', 'ideogram.ai', 'productive'),
    ('host', 'firefly.adobe.com', 'productive'),
    ('host', 'stability.ai', 'productive'),
    ('host', 'clipdrop.co', 'productive'),
    ('host', 'krea.ai', 'productive'),
    ('host', 'magnific.ai', 'productive'),
    ('host', 'recraft.ai', 'productive'),
    ('host', 'playground.com', 'productive'),
    ('host', 'freepik.com', 'productive'),
    ('host', 'flair.ai', 'productive'),
    ('host', 'photoroom.com', 'productive'),
    ('host', 'upscayl.org', 'productive'),
    ('host', 'nightcafe.studio', 'productive'),
    ('host', 'civitai.com', 'productive'),
    ('host', 'labs.google', 'productive'),
    ('host', 'aistudio.google.com', 'productive'),
    ('host', 'deepmind.google', 'productive'),
    ('host', 'notebooklm.google.com', 'productive'),
    ('host', 'gemini.google.com', 'productive'),
    ('host', 'jasper.ai', 'productive'),
    ('host', 'copy.ai', 'productive'),
    ('host', 'writesonic.com', 'productive'),
    ('host', 'rytr.me', 'productive'),
    ('host', 'quillbot.com', 'productive'),
    ('host', 'grammarly.com', 'productive'),
    ('host', 'wordtune.com', 'productive'),
    ('host', 'sudowrite.com', 'productive'),
    ('host', 'lex.page', 'productive'),
    ('host', 'elicit.com', 'productive'),
    ('host', 'consensus.app', 'productive'),
    ('host', 'scite.ai', 'productive'),
    ('host', 'semanticscholar.org', 'productive'),
    ('host', 'deepl.com', 'productive'),
    ('host', 'linguee.com', 'productive'),
    ('host', 'otter.ai', 'productive'),
    ('host', 'notta.ai', 'productive'),
    ('host', 'tldv.io', 'productive'),
    ('host', 'grain.com', 'productive'),
    ('host', 'avoma.com', 'productive'),
    ('host', 'circleback.ai', 'productive'),
    ('host', 'granola.ai', 'productive'),
    ('host', 'read.ai', 'productive'),
    ('host', 'gamma.app', 'productive'),
    ('host', 'tome.app', 'productive'),
    ('host', 'beautiful.ai', 'productive'),
    ('host', 'napkin.ai', 'productive'),
    ('host', 'eraser.io', 'productive'),
    ('host', 'mermaidchart.com', 'productive'),
    ('host', 'chatprd.ai', 'productive'),
    ('host', 'replicate.com', 'productive'),
    ('host', 'together.ai', 'productive'),
    ('host', 'groq.com', 'productive'),
    ('host', 'openrouter.ai', 'productive'),
    ('host', 'fal.ai', 'productive'),
    ('host', 'modal.com', 'productive'),
    ('host', 'runpod.io', 'productive'),
    ('host', 'lambdalabs.com', 'productive'),
    ('host', 'baseten.co', 'productive'),
    ('host', 'langchain.com', 'productive'),
    ('host', 'smith.langchain.com', 'productive'),
    ('host', 'llamaindex.ai', 'productive'),
    ('host', 'crewai.com', 'productive'),
    ('host', 'langflow.org', 'productive'),
    ('host', 'flowiseai.com', 'productive'),
    ('host', 'dify.ai', 'productive'),
    ('host', 'n8n.io', 'productive'),
    ('host', 'make.com', 'productive'),
    ('host', 'zapier.com', 'productive'),
    ('host', 'pipedream.com', 'productive'),
    ('host', 'windmill.dev', 'productive'),
    ('host', 'pinecone.io', 'productive'),
    ('host', 'weaviate.io', 'productive'),
    ('host', 'qdrant.tech', 'productive'),
    ('host', 'trychroma.com', 'productive'),
    ('host', 'milvus.io', 'productive'),
    ('host', 'wandb.ai', 'productive'),
    ('host', 'comet.com', 'productive'),
    ('host', 'neptune.ai', 'productive'),
    ('host', 'mlflow.org', 'productive'),
    ('host', 'labelbox.com', 'productive'),
    ('host', 'scale.com', 'productive'),
    ('host', 'roboflow.com', 'productive'),
    ('host', 'ultralytics.com', 'productive'),
    ('host', 'cursor.com', 'productive'),
    ('host', 'codeium.com', 'productive'),
    ('host', 'tabnine.com', 'productive'),
    ('host', 'sourcegraph.com', 'productive'),
    ('host', 'sweep.dev', 'productive'),
    ('host', 'codium.ai', 'productive'),
    ('host', 'qodo.ai', 'productive'),
    ('app', 'ChatGPT', 'productive'),
    ('app', 'Claude', 'productive'),
    ('app', 'Ollama', 'productive'),
    ('app', 'LM Studio', 'productive'),
    ('app', 'Jan', 'productive'),
    ('app', 'GPT4All', 'productive'),
    ('app', 'ComfyUI', 'productive'),
    ('app', 'Msty', 'productive'),
    ('app', 'AnythingLLM', 'productive'),
    ('app', 'Topaz Photo AI', 'productive'),
    ('app', 'Topaz Video AI', 'productive'),
    ('app', 'Topaz Gigapixel AI', 'productive'),
    ('app', 'Descript', 'productive'),
    ('app', 'CapCut', 'productive'),
    ('app', 'Adobe Firefly', 'productive'),
    ('app', 'Grammarly', 'productive'),
    ('app', 'GrammarlyInstaller', 'productive'),
    ('app', 'DeepL', 'productive'),
    ('app', 'ElevenLabs', 'productive'),
    ('app', 'HeyGen', 'productive'),
    ('app', 'NotebookLM', 'productive'),
    ('app', 'Perplexity', 'productive'),
    ('app', 'Raycast', 'productive'),
    ('app', 'Alfred', 'productive'),
    ('host', 'spline.design', 'productive'),
    ('host', 'rive.app', 'productive'),
    ('host', 'zeplin.io', 'productive'),
    ('host', 'protopie.io', 'productive'),
    ('host', 'marvelapp.com', 'productive'),
    ('host', 'invisionapp.com', 'productive'),
    ('host', 'balsamiq.com', 'productive'),
    ('host', 'uizard.io', 'productive'),
    ('host', 'relume.io', 'productive'),
    ('host', 'awwwards.com', 'productive'),
    ('host', 'mobbin.com', 'productive'),
    ('host', 'land-book.com', 'productive'),
    ('host', 'godly.website', 'productive'),
    ('host', 'savee.it', 'productive'),
    ('host', 'pinterest.com', 'productive'),
    ('host', 'siteinspire.com', 'productive'),
    ('host', 'refero.design', 'productive'),
    ('host', 'realtimecolors.com', 'productive'),
    ('host', 'uicolors.app', 'productive'),
    ('host', 'colorhunt.co', 'productive'),
    ('host', 'huemint.com', 'productive'),
    ('host', 'fontshare.com', 'productive'),
    ('host', 'befonts.com', 'productive'),
    ('host', 'dafont.com', 'productive'),
    ('host', 'myfonts.com', 'productive'),
    ('host', 'fonts.adobe.com', 'productive'),
    ('host', 'type.today', 'productive'),
    ('host', 'fontsinuse.com', 'productive'),
    ('host', 'blush.design', 'productive'),
    ('host', 'humaaans.com', 'productive'),
    ('host', 'openpeeps.com', 'productive'),
    ('host', 'iconscout.com', 'productive'),
    ('host', 'streamlinehq.com', 'productive'),
    ('host', 'phosphoricons.com', 'productive'),
    ('host', 'tabler-icons.io', 'productive'),
    ('host', 'svgrepo.com', 'productive'),
    ('host', 'vectorstock.com', 'productive'),
    ('host', 'shutterstock.com', 'productive'),
    ('host', 'gettyimages.com', 'productive'),
    ('host', 'istockphoto.com', 'productive'),
    ('host', 'adobestock.com', 'productive'),
    ('host', 'envato.com', 'productive'),
    ('host', 'elements.envato.com', 'productive'),
    ('host', 'creativemarket.com', 'productive'),
    ('host', 'uplabs.com', 'productive'),
    ('host', 'ui8.net', 'productive'),
    ('host', 'lapa.ninja', 'productive'),
    ('host', 'haikei.app', 'productive'),
    ('host', 'shapedivider.app', 'productive'),
    ('host', 'getwaves.io', 'productive'),
    ('host', 'pattern.monster', 'productive'),
    ('host', 'cssgradient.io', 'productive'),
    ('host', 'neumorphism.io', 'productive'),
    ('host', 'glassmorphism.com', 'productive'),
    ('host', 'responsively.app', 'productive'),
    ('host', 'polypane.app', 'productive'),
    ('host', 'browserling.com', 'productive'),
    ('app', 'Spline', 'productive'),
    ('app', 'Rive', 'productive'),
    ('app', 'Zeplin', 'productive'),
    ('app', 'Balsamiq Wireframes', 'productive'),
    ('app', 'Axure RP', 'productive'),
    ('app', 'Justinmind', 'productive'),
    ('app', 'ProtoPie', 'productive'),
    ('app', 'Principle', 'productive'),
    ('app', 'Pixelmator Pro', 'productive'),
    ('app', 'Capture One', 'productive'),
    ('app', 'Luminar Neo', 'productive'),
    ('app', 'DxO PhotoLab', 'productive'),
    ('app', 'ON1 Photo RAW', 'productive'),
    ('app', 'Nuke', 'productive'),
    ('app', 'NukeX', 'productive'),
    ('app', 'Houdini', 'productive'),
    ('app', 'houdinifx', 'productive'),
    ('app', 'Marmoset Toolbag', 'productive'),
    ('app', 'Marvelous Designer', 'productive'),
    ('app', 'Clip Studio Paint', 'productive'),
    ('app', 'CLIPStudioPaint', 'productive'),
    ('app', 'Procreate', 'productive'),
    ('app', 'Aseprite', 'productive'),
    ('app', 'Paint.NET', 'productive'),
    ('app', 'paintdotnet', 'productive'),
    ('app', 'PaintTool SAI', 'productive'),
    ('app', 'MediBang Paint', 'productive'),
    ('app', 'Vectornator', 'productive'),
    ('app', 'Linearity Curve', 'productive'),
    ('app', 'Graphite', 'productive'),
    ('app', 'Penpot', 'productive'),
    ('app', 'Adobe Substance 3D Designer', 'productive'),
    ('app', 'Adobe Dimension', 'productive'),
    ('app', 'Adobe Character Animator', 'productive'),
    ('app', 'Adobe Media Encoder', 'productive'),
    ('app', 'Adobe Fresco', 'productive'),
    ('app', 'Adobe InCopy', 'productive'),
    ('app', 'Adobe Illustrator Draw', 'productive'),
    ('host', 'braze.com', 'productive'),
    ('host', 'iterable.com', 'productive'),
    ('host', 'onesignal.com', 'productive'),
    ('host', 'moengage.com', 'productive'),
    ('host', 'clevertap.com', 'productive'),
    ('host', 'webengage.com', 'productive'),
    ('host', 'netcorecloud.com', 'productive'),
    ('host', 'mailerlite.com', 'productive'),
    ('host', 'omnisend.com', 'productive'),
    ('host', 'drip.com', 'productive'),
    ('host', 'attentive.com', 'productive'),
    ('host', 'postscript.io', 'productive'),
    ('host', 'customerio.com', 'productive'),
    ('host', 'intercom.io', 'productive'),
    ('host', 'gorgias.com', 'productive'),
    ('host', 'kustomer.com', 'productive'),
    ('host', 'gladly.com', 'productive'),
    ('host', 'richpanel.com', 'productive'),
    ('host', 'yotpo.com', 'productive'),
    ('host', 'judge.me', 'productive'),
    ('host', 'okendo.co', 'productive'),
    ('host', 'stamped.io', 'productive'),
    ('host', 'trustpilot.com', 'productive'),
    ('host', 'loyaltylion.com', 'productive'),
    ('host', 'smile.io', 'productive'),
    ('host', 'refersion.com', 'productive'),
    ('host', 'impact.com', 'productive'),
    ('host', 'partnerstack.com', 'productive'),
    ('host', 'everflow.io', 'productive'),
    ('host', 'tapfiliate.com', 'productive'),
    ('host', 'appsflyer.com', 'productive'),
    ('host', 'adjust.com', 'productive'),
    ('host', 'branch.io', 'productive'),
    ('host', 'kochava.com', 'productive'),
    ('host', 'singular.net', 'productive'),
    ('host', 'tenjin.com', 'productive'),
    ('host', 'airbridge.io', 'productive'),
    ('host', 'adsmanager.facebook.com', 'productive'),
    ('host', 'business.facebook.com', 'productive'),
    ('host', 'business.meta.com', 'productive'),
    ('host', 'meta.com', 'productive'),
    ('host', 'developers.facebook.com', 'productive'),
    ('host', 'creator.instagram.com', 'productive'),
    ('host', 'business.instagram.com', 'productive'),
    ('host', 'ads.pinterest.com', 'productive'),
    ('host', 'ads.snapchat.com', 'productive'),
    ('host', 'ads.reddit.com', 'productive'),
    ('host', 'ads.microsoft.com', 'productive'),
    ('host', 'advertising.amazon.com', 'productive'),
    ('host', 'business.tiktok.com', 'productive'),
    ('host', 'ads.tiktok.com', 'productive'),
    ('host', 'displayvideo.google.com', 'productive'),
    ('host', 'admanager.google.com', 'productive'),
    ('host', 'adsense.google.com', 'productive'),
    ('host', 'taboola.com', 'productive'),
    ('host', 'outbrain.com', 'productive'),
    ('host', 'criteo.com', 'productive'),
    ('host', 'thetradedesk.com', 'productive'),
    ('host', 'stackadapt.com', 'productive'),
    ('host', 'quora.com/business', 'productive'),
    ('host', 'ads.x.com', 'productive'),
    ('host', 'ads.spotify.com', 'productive'),
    ('host', 'heap.io', 'productive'),
    ('host', 'fullstory.com', 'productive'),
    ('host', 'clarity.microsoft.com', 'productive'),
    ('host', 'plausible.io', 'productive'),
    ('host', 'usefathom.com', 'productive'),
    ('host', 'matomo.org', 'productive'),
    ('host', 'rudderstack.com', 'productive'),
    ('host', 'mparticle.com', 'productive'),
    ('host', 'snowplow.io', 'productive'),
    ('host', 'countly.com', 'productive'),
    ('host', 'smartlook.com', 'productive'),
    ('host', 'contentsquare.com', 'productive'),
    ('host', 'quantummetric.com', 'productive'),
    ('host', 'glassbox.com', 'productive'),
    ('host', 'sisense.com', 'productive'),
    ('host', 'domo.com', 'productive'),
    ('host', 'qlik.com', 'productive'),
    ('host', 'thoughtspot.com', 'productive'),
    ('host', 'hex.tech', 'productive'),
    ('host', 'mode.com', 'productive'),
    ('host', 'preset.io', 'productive'),
    ('host', 'superset.apache.org', 'productive'),
    ('host', 'holistics.io', 'productive'),
    ('host', 'zoho.com/analytics', 'productive'),
    ('host', 'databox.com', 'productive'),
    ('host', 'klipfolio.com', 'productive'),
    ('host', 'geckoboard.com', 'productive'),
    ('host', 'whatagraph.com', 'productive'),
    ('host', 'improvado.io', 'productive'),
    ('host', 'funnel.io', 'productive'),
    ('host', 'supermetrics.com', 'productive'),
    ('host', 'screamingfrog.co.uk', 'productive'),
    ('host', 'sistrix.com', 'productive'),
    ('host', 'majestic.com', 'productive'),
    ('host', 'seranking.com', 'productive'),
    ('host', 'surferseo.com', 'productive'),
    ('host', 'clearscope.io', 'productive'),
    ('host', 'marketmuse.com', 'productive'),
    ('host', 'frase.io', 'productive'),
    ('host', 'keywordtool.io', 'productive'),
    ('host', 'answerthepublic.com', 'productive'),
    ('host', 'sparktoro.com', 'productive'),
    ('host', 'contentking.com', 'productive'),
    ('host', 'oncrawl.com', 'productive'),
    ('host', 'deepcrawl.com', 'productive'),
    ('host', 'botify.com', 'productive'),
    ('host', 'pagespeed.web.dev', 'productive'),
    ('host', 'gtmetrix.com', 'productive'),
    ('host', 'webpagetest.org', 'productive'),
    ('host', 'search.google.com/search-console', 'productive'),
    ('host', 'bing.com/webmasters', 'productive'),
    ('host', 'agorapulse.com', 'productive'),
    ('host', 'socialpilot.co', 'productive'),
    ('host', 'publer.io', 'productive'),
    ('host', 'metricool.com', 'productive'),
    ('host', 'brandwatch.com', 'productive'),
    ('host', 'mention.com', 'productive'),
    ('host', 'talkwalker.com', 'productive'),
    ('host', 'meltwater.com', 'productive'),
    ('host', 'iconosquare.com', 'productive'),
    ('host', 'planoly.com', 'productive'),
    ('host', 'tailwindapp.com', 'productive'),
    ('host', 'studio.youtube.com', 'productive'),
    ('host', 'creatorstudio.facebook.com', 'productive'),
    ('host', 'unbounce.com', 'productive'),
    ('host', 'instapage.com', 'productive'),
    ('host', 'leadpages.com', 'productive'),
    ('host', 'clickfunnels.com', 'productive'),
    ('host', 'convertflow.com', 'productive'),
    ('host', 'optimizely.com', 'productive'),
    ('host', 'vwo.com', 'productive'),
    ('host', 'abtasty.com', 'productive'),
    ('host', 'growthbook.io', 'productive'),
    ('host', 'statsig.com', 'productive'),
    ('host', 'launchdarkly.com', 'productive'),
    ('host', 'split.io', 'productive'),
    ('host', 'typeform.com', 'productive'),
    ('host', 'jotform.com', 'productive'),
    ('host', 'surveymonkey.com', 'productive'),
    ('host', 'tally.so', 'productive'),
    ('host', 'formstack.com', 'productive'),
    ('host', 'qualtrics.com', 'productive'),
    ('host', 'usertesting.com', 'productive'),
    ('host', 'maze.co', 'productive'),
    ('host', 'lookback.com', 'productive'),
    ('host', 'dovetail.com', 'productive'),
    ('host', 'shopify.com', 'productive'),
    ('host', 'admin.shopify.com', 'productive'),
    ('host', 'woocommerce.com', 'productive'),
    ('host', 'bigcommerce.com', 'productive'),
    ('host', 'magento.com', 'productive'),
    ('host', 'squarespace.com', 'productive'),
    ('host', 'wix.com', 'productive'),
    ('host', 'wordpress.org', 'productive'),
    ('host', 'wordpress.com', 'productive'),
    ('host', 'contentful.com', 'productive'),
    ('host', 'sanity.io', 'productive'),
    ('host', 'storyblok.com', 'productive'),
    ('host', 'strapi.io', 'productive'),
    ('host', 'prismic.io', 'productive'),
    ('host', 'directus.io', 'productive'),
    ('host', 'ghost.org', 'productive'),
    ('host', 'hashnode.com', 'productive'),
    ('host', 'substack.com', 'productive'),
    ('host', 'beehiiv.com', 'productive'),
    ('host', 'sellercentral.amazon.in', 'productive'),
    ('host', 'sellercentral.amazon.com', 'productive'),
    ('host', 'seller.flipkart.com', 'productive'),
    ('host', 'supplier.meesho.com', 'productive'),
    ('host', 'partner.myntra.com', 'productive'),
    ('host', 'seller.ajio.com', 'productive'),
    ('host', 'unicommerce.com', 'productive'),
    ('host', 'shiprocket.in', 'productive'),
    ('host', 'delhivery.com', 'productive'),
    ('app', 'HubSpot', 'productive'),
    ('app', 'Salesforce', 'productive'),
    ('app', 'Pipedrive', 'productive'),
    ('app', 'Zoho CRM', 'productive'),
    ('app', 'Mailchimp', 'productive'),
    ('app', 'Klaviyo', 'productive'),
    ('app', 'Canva', 'productive'),
    ('app', 'Buffer', 'productive'),
    ('app', 'Hootsuite', 'productive'),
    ('app', 'Later', 'productive'),
    ('app', 'Sprout Social', 'productive'),
    ('app', 'Semrush', 'productive'),
    ('app', 'Ahrefs', 'productive'),
    ('app', 'Screaming Frog SEO Spider', 'productive'),
    ('app', 'ScreamingFrogSEOSpider', 'productive'),
    ('app', 'Tableau Desktop', 'productive'),
    ('app', 'Power BI Desktop', 'productive'),
    ('app', 'PBIDesktop', 'productive'),
    ('app', 'Looker Studio', 'productive'),
    ('app', 'Google Ads Editor', 'productive'),
    ('app', 'Google Web Designer', 'productive'),
    ('app', 'Meta Business Suite', 'productive'),
    ('app', 'Loom', 'productive'),
    ('app', 'Vidyard', 'productive'),
    ('app', 'Vimeo', 'productive'),
    ('app', 'Riverside', 'productive'),
    ('app', 'StreamYard', 'productive'),
    ('app', 'Audacity', 'productive'),
    ('app', 'Reaper', 'productive'),
    ('app', 'Ableton Live', 'productive'),
    ('app', 'FL Studio', 'productive'),
    ('app', 'Logic Pro', 'productive'),
    ('app', 'Pro Tools', 'productive'),
    ('app', 'Studio One', 'productive'),
    ('app', 'Cubase', 'productive'),
    ('host', 'facebook.com', 'neutral'),
    ('host', 'instagram.com', 'neutral'),
    ('host', 'x.com', 'neutral'),
    ('host', 'twitter.com', 'neutral'),
    ('host', 'linkedin.com', 'neutral'),
    ('host', 'tiktok.com', 'neutral'),
    ('host', 'youtube.com', 'neutral'),
    ('host', 'reddit.com', 'neutral'),
    ('host', 'threads.net', 'neutral'),
    ('host', 'snapchat.com', 'neutral'),
    ('host', 'web.whatsapp.com', 'neutral'),
    ('host', 'whatsapp.com', 'neutral'),
    ('host', 'telegram.org', 'neutral'),
    ('host', 'web.telegram.org', 'neutral'),
    ('host', 'quora.com', 'neutral'),
    ('host', 'medium.com', 'neutral')
  ),
  ins AS (
    INSERT INTO public.productivity_rules (org_id, match_type, pattern, category, department)
    SELECT p_org_id, c.match_type, c.pattern, c.category, NULL
    FROM catalogue c
    -- Never overwrite an admin's decision, and never fight the earlier
    -- catalogues: whatever is already there for a pattern wins.
    ON CONFLICT (org_id, match_type, pattern, department) DO NOTHING
    RETURNING 1
  )
  SELECT count(*) INTO v_inserted FROM ins;
  RETURN v_inserted;
END
$fn$;

COMMENT ON FUNCTION public.seed_ai_design_martech_rules(uuid) IS
  'Extends the default catalogue with generative-AI, design, martech, '
  'analytics, SEO, social-management and e-commerce tooling. Social platforms '
  'are seeded neutral (dual-use) while their business surfaces are productive. '
  'Idempotent and non-destructive.';

DO $do$
DECLARE r record; n integer; total integer := 0;
BEGIN
  FOR r IN SELECT id FROM public.organizations LOOP
    SELECT public.seed_ai_design_martech_rules(r.id) INTO n;
    total := total + n;
  END LOOP;
  RAISE NOTICE 'seeded % AI/design/martech rules across all organisations', total;
END $do$;

-- Fold into new-organisation seeding alongside the existing catalogues.
CREATE OR REPLACE FUNCTION public.tg_seed_org_productivity_rules()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $tg$
BEGIN
  PERFORM public.seed_default_productivity_rules(NEW.id);
  PERFORM public.seed_prohibited_rules(NEW.id);
  PERFORM public.seed_rotating_domain_rules(NEW.id);
  PERFORM public.seed_ai_design_martech_rules(NEW.id);
  RETURN NULL;
EXCEPTION WHEN OTHERS THEN
  RAISE WARNING 'could not seed default productivity rules for org %: %', NEW.id, SQLERRM;
  RETURN NULL;
END
$tg$;

NOTIFY pgrst, 'reload schema';
